// Generated by hand from db/schema.sql / prisma/schema.prisma. Update
// all three when an enum changes (db/schema.sql is canonical).
//
// Each enum is exported as both a const object (runtime values) and a
// type alias (compile-time union). Migrated SQL queries pass the enum
// values as bind parameters, and downstream code uses the type alias
// for narrowing. After U12 deletes Prisma, this file is the only
// source of enum identifiers in the codebase.

export const AcquisitionJobStatus = {
  QUEUED: "QUEUED",
  RUNNING: "RUNNING",
  SUCCEEDED: "SUCCEEDED",
  PARTIAL: "PARTIAL",
  FAILED: "FAILED",
  DISABLED: "DISABLED",
  DEAD_LETTER: "DEAD_LETTER",
} as const;
export type AcquisitionJobStatus = (typeof AcquisitionJobStatus)[keyof typeof AcquisitionJobStatus];

export const AcquisitionProvider = {
  X_API: "X_API",
  LINKEDIN_API: "LINKEDIN_API",
  GITHUB_API: "GITHUB_API",
  YOUTUBE_API: "YOUTUBE_API",
  RSS: "RSS",
  SPIDER: "SPIDER",
  PARALLEL: "PARALLEL",
  MANUAL: "MANUAL",
  INSTAGRAM_GRAPH: "INSTAGRAM_GRAPH",
} as const;
export type AcquisitionProvider = (typeof AcquisitionProvider)[keyof typeof AcquisitionProvider];

export const DataReadiness = {
  PUBLIC_ONLY: "PUBLIC_ONLY",
  MANUAL_IMPORT: "MANUAL_IMPORT",
  LIVE: "LIVE",
} as const;
export type DataReadiness = (typeof DataReadiness)[keyof typeof DataReadiness];

export const IntentClass = {
  THREE_POINT: "THREE_POINT",
  MID_RANGE: "MID_RANGE",
  PAINT: "PAINT",
  FREE_THROW: "FREE_THROW",
  PASS: "PASS",
} as const;
export type IntentClass = (typeof IntentClass)[keyof typeof IntentClass];

export const MetricConfidence = {
  DIRECT: "DIRECT",
  ESTIMATED: "ESTIMATED",
  MODELED: "MODELED",
  HYPOTHESIS: "HYPOTHESIS",
  NEEDS_INTERNAL_ANALYTICS: "NEEDS_INTERNAL_ANALYTICS",
} as const;
export type MetricConfidence = (typeof MetricConfidence)[keyof typeof MetricConfidence];

export const Platform = {
  X: "X",
  LINKEDIN: "LINKEDIN",
  GITHUB: "GITHUB",
  INSTAGRAM: "INSTAGRAM",
  NEWSLETTER: "NEWSLETTER",
  YOUTUBE: "YOUTUBE",
  PODCAST: "PODCAST",
  LAUNCHES: "LAUNCHES",
  TEAMMATE_AMPLIFICATION: "TEAMMATE_AMPLIFICATION",
  EXTERNAL_AMPLIFICATION: "EXTERNAL_AMPLIFICATION",
  PRODUCT_HUNT: "PRODUCT_HUNT",
  PERSONAL_SITE: "PERSONAL_SITE",
  TIKTOK: "TIKTOK",
  WEBSITE: "WEBSITE",
  SUBSTACK: "SUBSTACK",
  APP_STORE: "APP_STORE",
  REFERRAL: "REFERRAL",
  CONSULTING: "CONSULTING",
} as const;
export type Platform = (typeof Platform)[keyof typeof Platform];

export const ShotOutcome = {
  MADE: "MADE",
  MISSED: "MISSED",
  TURNOVER: "TURNOVER",
} as const;
export type ShotOutcome = (typeof ShotOutcome)[keyof typeof ShotOutcome];

export const SourceReadiness = {
  READY: "READY",
  MANUAL_IMPORT: "MANUAL_IMPORT",
  NEEDS_OAUTH: "NEEDS_OAUTH",
  FUTURE: "FUTURE",
} as const;
export type SourceReadiness = (typeof SourceReadiness)[keyof typeof SourceReadiness];
