// Generated by hand from db/schema.sql. Update both when schema changes.
//
// Row-shape types for every public.* table. These match what `SELECT *`
// returns from PostgreSQL via @neondatabase/serverless: every column is
// present (use `T | null` for nullable columns; never `T?`, which would
// imply the column is missing).
//
// Enum types come from @/lib/db-enums (single source of identifier
// strings). When you change a schema field, change BOTH this file and
// db/schema.sql.
//
// Types are ordered alphabetically by name for diff stability.

import type {
  AcquisitionJobStatus,
  AcquisitionProvider,
  DataReadiness,
  IntentClass,
  MetricConfidence,
  Platform,
  ShotOutcome,
  SourceReadiness,
} from "@/lib/db-enums";

// ---------------------------------------------------------------------------
// Row types (alphabetical)
// ---------------------------------------------------------------------------

export type AcquisitionJob = {
  id: string;
  surfaceId: string;
  provider: AcquisitionProvider;
  status: AcquisitionJobStatus;
  idempotencyKey: string | null;
  attemptNumber: number;
  windowStart: Date;
  windowEnd: Date;
  attempts: number;
  nextAttemptAt: Date | null;
  deadLetterAt: Date | null;
  inngestRunId: string | null;
  rawCount: number;
  inserted: number;
  updated: number;
  skipped: number;
  failureCode: string | null;
  failureReason: string | null;
  startedAt: Date | null;
  completedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

export type AcquisitionRoute = {
  id: string;
  platform: Platform;
  provider: AcquisitionProvider;
  routeOrder: number;
  capability: string;
  requiredEnv: string | null;
  confidence: MetricConfidence;
  complianceNote: string;
  createdAt: Date;
  updatedAt: Date;
};

export type Company = {
  id: string;
  name: string;
  domain: string;
  website: string;
  slug: string | null;
  description: string | null;
  youtubeSubscribers: number | null;
  youtubeViews: number | null;
  youtubeVideos: number | null;
  newsletterSubscribers: number | null;
  xFollowers: number | null;
  linkedinFollowers: number | null;
  githubRepos: number | null;
  productHuntProducts: number | null;
  podcastEpisodes: number | null;
  teamSize: number | null;
  publicFacingCount: number | null;
  createdAt: Date;
  updatedAt: Date;
};

export type ConversionEvent = {
  id: string;
  redirectId: string | null;
  postId: string | null;
  entityType: string;
  entityId: string;
  eventType: string;
  referrerUrl: string | null;
  utmCampaign: string | null;
  utmMedium: string | null;
  utmContent: string | null;
  userAgent: string | null;
  ipAddress: string | null;
  occurredAt: Date;
};

export type DataSource = {
  id: string;
  name: string;
  category: string;
  readiness: SourceReadiness;
  confidence: MetricConfidence;
  description: string;
  createdAt: Date;
  updatedAt: Date;
};

export type DiscoveredSurface = {
  id: string;
  employeeId: string;
  surface: string;
  label: string;
  handle: string | null;
  url: string | null;
  status: string;
  discoveryMethod: string;
  discoveredAt: Date;
  lastVerifiedAt: Date | null;
  confidenceScore: number;
  evidence: string[];
  notes: string | null;
  searchQuery: string | null;
  searchRank: number | null;
  createdAt: Date;
  updatedAt: Date;
};

export type DiscoveryJob = {
  id: string;
  jobType: string;
  status: string;
  employeeId: string | null;
  surface: string | null;
  surfacesFound: number;
  surfacesUpdated: number;
  errors: string[];
  startedAt: Date | null;
  completedAt: Date | null;
  createdAt: Date;
};

export type Employee = {
  id: string;
  companyId: string;
  name: string;
  role: string;
  archetype: string | null;
  dataReadiness: DataReadiness;
  primarySurface: Platform;
  secondarySurface: Platform;
  signatureMove: string;
  opportunity: string;
  bestShot: string;
  bestAssist: string;
  surfacePresence: number;
  surfaceIQ: number;
  trustGravity: number;
  socialTS: number;
  shotDistribution: unknown; // Json
  xFollowers: number | null;
  isPublicFacing: boolean;
  recommendedPlayId: string | null;
  createdAt: Date;
  updatedAt: Date;
};

export type Experiment = {
  id: string;
  playId: string;
  ownerEmployeeId: string;
  name: string;
  hypothesis: string;
  status: string;
  metric: string;
  createdAt: Date;
  updatedAt: Date;
};

export type Metric = {
  id: string;
  employeeId: string;
  surfaceId: string;
  platform: Platform;
  timeWindow: string;
  windowStart: Date;
  windowEnd: Date | null;
  posts: number;
  views: number;
  reach: number;
  likes: number;
  comments: number;
  replies: number;
  reposts: number;
  quotes: number;
  shares: number;
  clicks: number;
  profileVisits: number;
  signups: number;
  paidSubscriptions: number;
  consultingLeads: number;
  revenue: number;
  assistedConversions: number;
  surfaceIQ: number;
  socialTS: number;
  assistRate: number;
  trustGravity: number;
  totalAttempts: number;
  threePtAttempts: number;
  midAttempts: number;
  paintAttempts: number;
  ftAttempts: number;
  ftMade: number;
  passes: number;
  turnovers: number;
  threePtMade: number;
  midMade: number;
  paintMade: number;
  threePtPct: number;
  midPct: number;
  paintPct: number;
  fgPct: number;
  effectiveFgPct: number;
  trueShootingPct: number;
  pacePerWeek: number;
  brandTouchEvery: number;
  brandTouchPersonal: number;
  assistsCreated: number;
  createdAt: Date;
  updatedAt: Date;
};

export type Play = {
  id: string;
  name: string;
  bestFor: string;
  bestPlatforms: Platform[];
  structure: string;
  whyItWorks: string;
  historicalSignal: string;
  recommendedNextExperiment: string;
};

export type Post = {
  id: string;
  employeeId: string;
  surfaceId: string | null;
  text: string;
  platform: Platform;
  contentType: string;
  archetype: string;
  campaign: string;
  ctaType: string;
  brandTouch: string;
  product: string;
  launchWindow: boolean;
  publishedAt: Date;
  x: number;
  y: number;
  zone: string;
  advancedZone: string;
  intentClass: IntentClass;
  intentConfidence: number;
  outcome: ShotOutcome;
  recovered: boolean;
  isAssist: boolean;
  classifiedAt: Date | null;
  classifiedBy: string | null;
  confidence: MetricConfidence;
  externalId: string | null;
  permalink: string | null;
  rawActivityId: string | null;
  acquiredVia: AcquisitionProvider | null;
  acquiredAt: Date | null;
  sourceId: string | null;
  recommendedPlayId: string | null;
  createdAt: Date;
  updatedAt: Date;
};

export type PostMetrics = {
  id: string;
  postId: string;
  views: number;
  reach: number;
  likes: number;
  comments: number;
  replies: number;
  reposts: number;
  quotes: number;
  shares: number;
  clicks: number;
  profileVisits: number;
  signups: number;
  paidSubscriptions: number;
  consultingLeads: number;
  revenue: number;
  assistedConversions: number;
};

export type PostScores = {
  id: string;
  postId: string;
  awareness: number;
  engagement: number;
  trust: number;
  clicks: number;
  signups: number;
  paid: number;
  consulting: number;
  revenue: number;
  assists: number;
  surfaceIQ: number;
  socialTS: number;
  assistRate: number;
  trustGravity: number;
  humanHalo: number;
};

export type ProviderBudget = {
  id: string;
  provider: AcquisitionProvider;
  day: Date;
  used: number;
  cap: number;
  createdAt: Date;
  updatedAt: Date;
};

export type RawActivity = {
  id: string;
  surfaceId: string;
  jobId: string | null;
  provider: AcquisitionProvider;
  externalId: string;
  permalink: string | null;
  publishedAt: Date;
  text: string;
  rawMetrics: unknown; // Json
  rawPayload: unknown; // Json
  citations: unknown; // Json
  basis: unknown | null; // Json?
  confidence: MetricConfidence;
  createdAt: Date;
  updatedAt: Date;
};

export type RawPost = {
  id: string;
  platform: string;
  nativeId: string;
  entityType: string;
  entityId: string;
  content: string;
  contentType: string;
  url: string | null;
  mediaUrl: string | null;
  postedAt: Date;
  collectedAt: Date;
  rawReach: number | null;
  rawLikes: number | null;
  rawReplies: number | null;
  rawReposts: number | null;
  rawClicks: number | null;
  rawOpens: number | null;
  rawComments: number | null;
  rawStars: number | null;
  rawForks: number | null;
  rawMetrics: unknown | null; // Json?
  extractedUrls: string[];
  rawHash: string;
  normalizedToPostId: string | null;
};

export type Report = {
  id: string;
  companyId: string;
  title: string;
  period: string;
  status: string;
  summary: string;
  createdAt: Date;
  updatedAt: Date;
};

export type RippleEvent = {
  id: string;
  rootPostId: string;
  parentId: string | null;
  employeeId: string | null;
  actor: string;
  platform: Platform;
  eventType: string;
  occurredAt: Date;
  value: number;
  confidence: MetricConfidence;
};

export type SocialAccount = {
  id: string;
  employeeId: string;
  platform: Platform;
  handle: string;
  followers: number;
  confidence: MetricConfidence;
  createdAt: Date;
  updatedAt: Date;
};

export type Surface = {
  id: string;
  companyId: string;
  employeeId: string | null;
  platform: Platform;
  handle: string;
  url: string | null;
  present: boolean;
  status: string;
  followers: number;
  confidence: MetricConfidence;
  lastScrapedAt: Date | null;
  attributionValue: string | null;
  opportunity: string | null;
  createdAt: Date;
  updatedAt: Date;
};

export type TrackedRedirect = {
  id: string;
  shortId: string;
  postId: string | null;
  destinationUrl: string;
  clickCount: number;
  utmCampaign: string | null;
  utmMedium: string | null;
  utmContent: string | null;
  createdAt: Date;
};
