import type {
  DataSource,
  Employee,
  Experiment,
  Play,
  Post,
  RippleEvent,
  SocialAccount,
} from "@/lib/types";

export const employees: Employee[] = [
  {
    id: "austin",
    name: "Austin Tedesco",
    role: "Head of Growth",
    archetype: "Growth Playmaker",
    primarySurface: "X",
    secondarySurface: "LinkedIn",
    signatureMove: "Practical growth and AI posts that create trust and downstream conversion",
    opportunity: "Newsletter conversion bridge",
    bestShot: "X practical growth breakdowns that convert into newsletter signups",
    bestAssist: "Quote-posting teammate launches with concrete operator takeaways",
    surfacePresence: 88,
    surfaceIQ: 84,
    trustGravity: 79,
    socialTS: 64.5,
    shotDistribution: { X: 46, LinkedIn: 31, Newsletter: 9, Amplification: 14 },
    recommendedPlayId: "play-newsletter-bridge",
  },
  {
    id: "dan",
    name: "Dan Shipper",
    role: "Founder/CEO",
    archetype: "Founder Engine",
    primarySurface: "Newsletter",
    secondarySurface: "X",
    signatureMove: "Category creation and founder-led narrative",
    opportunity: "Teammate alley-oop amplification",
    bestShot: "Newsletter essays that create paid subscription and high-trust demand",
    bestAssist: "Founder narrative picked up by teammates and external operators",
    surfacePresence: 81,
    surfaceIQ: 89,
    trustGravity: 92,
    socialTS: 68.2,
    shotDistribution: { Newsletter: 42, X: 28, Podcast: 18, LinkedIn: 12 },
    recommendedPlayId: "play-teammate-alley-oop",
  },
  {
    id: "kieran",
    name: "Kieran Klaassen",
    role: "Product / Design / Builder",
    archetype: "Builder Philosopher",
    primarySurface: "X",
    secondarySurface: "GitHub",
    signatureMove: "Philosophical product posts that outperform direct promo",
    opportunity: "Product diary and design notes",
    bestShot: "Human product craft observations that build durable trust",
    bestAssist: "Technical proof that makes Austin and Dan conversion posts more credible",
    surfacePresence: 74,
    surfaceIQ: 78,
    trustGravity: 86,
    socialTS: 59.7,
    shotDistribution: { X: 44, GitHub: 24, Product: 18, LinkedIn: 14 },
    recommendedPlayId: "play-github-linkedin-proof",
  },
];

export const accounts: SocialAccount[] = [
  { id: "acct-austin-x", employeeId: "austin", platform: "X", handle: "@austintedesco", followers: 28600, confidence: "Estimated" },
  { id: "acct-austin-li", employeeId: "austin", platform: "LinkedIn", handle: "austin-tedesco", followers: 11800, confidence: "Estimated" },
  { id: "acct-dan-newsletter", employeeId: "dan", platform: "Newsletter", handle: "Every", followers: 96000, confidence: "Direct" },
  { id: "acct-dan-x", employeeId: "dan", platform: "X", handle: "@danshipper", followers: 74200, confidence: "Estimated" },
  { id: "acct-kieran-x", employeeId: "kieran", platform: "X", handle: "@kieranklaassen", followers: 18400, confidence: "Estimated" },
  { id: "acct-kieran-gh", employeeId: "kieran", platform: "GitHub", handle: "kieranklaassen", followers: 4200, confidence: "Direct" },
];

export const plays: Play[] = [
  {
    id: "play-soft-cta",
    name: "Soft CTA After Trust Post",
    bestFor: "Personal AI observations and operator lessons",
    bestPlatforms: ["X", "LinkedIn", "Newsletter"],
    structure: "Trust-building post first, low-friction newsletter bridge second, explicit CTA only after replies show intent.",
    whyItWorks: "It preserves the post's native feel while giving high-intent readers a clear next step.",
    historicalSignal: "Personal AI posts generated 2.3x more assisted signups when followed by a soft CTA within 24 hours.",
    recommendedNextExperiment: "Pair one high-trust Austin X thread with a newsletter reply CTA and teammate quote within two hours.",
  },
  {
    id: "play-teammate-alley-oop",
    name: "Teammate Alley-Oop",
    bestFor: "Founder narrative, launches, and category creation",
    bestPlatforms: ["X", "LinkedIn", "Teammate Amplification"],
    structure: "Root narrative from Dan, teammate quote-post with practical takeaway, follow-up reply pointing to owned surface.",
    whyItWorks: "The teammate adds proof and specificity without making the founder post feel like an ad.",
    historicalSignal: "Dan posts with teammate quote support produced 31% higher assisted conversions than solo posts.",
    recommendedNextExperiment: "Pre-brief two teammate quote angles before the next Every launch essay.",
  },
  {
    id: "play-linkedin-wedge",
    name: "LinkedIn Consulting Wedge",
    bestFor: "B2B intent and operator proof",
    bestPlatforms: ["LinkedIn"],
    structure: "Operator pain, Every method, concrete example, light invitation to discuss consulting.",
    whyItWorks: "LinkedIn reach is lower, but the audience has more budget authority and problem awareness.",
    historicalSignal: "Consulting posts with real operator framing converted at 4.7x the surface average.",
    recommendedNextExperiment: "Run two Austin LinkedIn posts with different wedges: automation audit vs AI operating system.",
  },
  {
    id: "play-human-halo",
    name: "Human Halo",
    bestFor: "Human affinity and trust around technical work",
    bestPlatforms: ["Instagram", "X", "Podcast"],
    structure: "Personal story, taste or belief, proof of work, no immediate conversion ask.",
    whyItWorks: "It builds familiarity that makes later conversion posts feel less cold.",
    historicalSignal: "Human Halo posts rarely close directly but show strong hockey assists 7 to 14 days later.",
    recommendedNextExperiment: "Use one behind-the-scenes product note before a product CTA push.",
  },
  {
    id: "play-launch-rotation",
    name: "Launch Rotation",
    bestFor: "Product and content launches",
    bestPlatforms: ["Launches", "X", "Newsletter", "LinkedIn"],
    structure: "Founder announcement, growth operator explanation, builder proof, external amplification target list.",
    whyItWorks: "Different surfaces cover awareness, proof, conversion, and credibility in sequence.",
    historicalSignal: "Launch windows show the best spacing and highest assisted conversion density.",
    recommendedNextExperiment: "Schedule founder, growth, and builder posts across a 36-hour launch rotation.",
  },
  {
    id: "play-newsletter-bridge",
    name: "Newsletter Conversion Bridge",
    bestFor: "Turning social trust into owned audience",
    bestPlatforms: ["X", "LinkedIn", "Newsletter"],
    structure: "Social insight, specific newsletter promise, landing link, teammate reply reinforcing why to subscribe.",
    whyItWorks: "It makes the owned channel feel like the next chapter instead of a generic signup ask.",
    historicalSignal: "Social posts with newsletter-specific promise beat generic signup CTAs by 38%.",
    recommendedNextExperiment: "Attach a newsletter promise to Austin's top X growth thread each week.",
  },
  {
    id: "play-github-linkedin-proof",
    name: "GitHub-to-LinkedIn Technical Proof",
    bestFor: "Technical credibility and consulting trust",
    bestPlatforms: ["GitHub", "LinkedIn"],
    structure: "Ship technical proof in public, translate the lesson into operator language on LinkedIn.",
    whyItWorks: "GitHub proves depth while LinkedIn makes the business implication legible.",
    historicalSignal: "Technical proof posts created fewer clicks but stronger consulting intent.",
    recommendedNextExperiment: "Turn Kieran's next repo note into a LinkedIn operator post within 48 hours.",
  },
];

export const posts: Post[] = [
  {
    id: "post-austin-ai-consulting",
    employeeId: "austin",
    text: "The best AI consulting pitch is not 'we use AI.' It is 'we can show your team the repetitive decision loops already costing you margin.'",
    platform: "X",
    contentType: "Original Post",
    archetype: "Growth Playmaker",
    campaign: "AI Consulting",
    ctaType: "Soft consulting CTA",
    brandTouch: "Every",
    product: "Consulting",
    launchWindow: false,
    timestamp: "2026-04-09T10:02:00-04:00",
    x: 24,
    y: 38,
    zone: "X",
    advancedZone: "X original posts",
    confidence: "Modeled",
    metrics: {
      views: 612000,
      reach: 710000,
      likes: 16200,
      comments: 580,
      replies: 430,
      reposts: 2100,
      quotes: 420,
      shares: 1800,
      clicks: 3800,
      profileVisits: 12200,
      signups: 486,
      paidSubscriptions: 42,
      consultingLeads: 9,
      revenue: 88000,
      assistedConversions: 310,
    },
    scores: {
      awareness: 92,
      engagement: 74,
      trust: 84,
      clicks: 78,
      signups: 91,
      paid: 74,
      consulting: 96,
      revenue: 89,
      assists: 83,
      surfaceIQ: 88,
      socialTS: 72,
      assistRate: 58,
      trustGravity: 86,
      humanHalo: 54,
    },
    recommendedPlayId: "play-linkedin-wedge",
  },
  {
    id: "post-austin-linkedin-operator",
    employeeId: "austin",
    text: "Most growth teams do not need more channels. They need a better read on which existing trust surfaces are already creating demand.",
    platform: "LinkedIn",
    contentType: "Operator Post",
    archetype: "Growth Playmaker",
    campaign: "Surface IQ",
    ctaType: "Consulting wedge",
    brandTouch: "Every",
    product: "Consulting",
    launchWindow: false,
    timestamp: "2026-04-12T09:21:00-04:00",
    x: 68,
    y: 42,
    zone: "LinkedIn",
    advancedZone: "LinkedIn operator posts",
    confidence: "Estimated",
    metrics: {
      views: 84000,
      reach: 108000,
      likes: 2100,
      comments: 164,
      replies: 48,
      reposts: 190,
      quotes: 28,
      shares: 450,
      clicks: 920,
      profileVisits: 2400,
      signups: 88,
      paidSubscriptions: 11,
      consultingLeads: 12,
      revenue: 124000,
      assistedConversions: 72,
    },
    scores: {
      awareness: 64,
      engagement: 69,
      trust: 88,
      clicks: 67,
      signups: 68,
      paid: 58,
      consulting: 98,
      revenue: 94,
      assists: 61,
      surfaceIQ: 91,
      socialTS: 76,
      assistRate: 64,
      trustGravity: 89,
      humanHalo: 49,
    },
    recommendedPlayId: "play-linkedin-wedge",
  },
  {
    id: "post-austin-hard-cta",
    employeeId: "austin",
    text: "We opened a few slots for AI workflow audits. If you want a sharper operating system, start here.",
    platform: "X",
    contentType: "Product CTA",
    archetype: "Growth Playmaker",
    campaign: "AI Consulting",
    ctaType: "Hard CTA",
    brandTouch: "Product",
    product: "Consulting",
    launchWindow: false,
    timestamp: "2026-04-18T15:12:00-04:00",
    x: 46,
    y: 53,
    zone: "Launches",
    advancedZone: "Product CTAs",
    confidence: "Needs Internal Analytics",
    metrics: {
      views: 92000,
      reach: 118000,
      likes: 850,
      comments: 42,
      replies: 36,
      reposts: 88,
      quotes: 18,
      shares: 84,
      clicks: 1800,
      profileVisits: 1300,
      signups: 104,
      paidSubscriptions: 9,
      consultingLeads: 6,
      revenue: 76000,
      assistedConversions: 38,
    },
    scores: {
      awareness: 58,
      engagement: 32,
      trust: 48,
      clicks: 72,
      signups: 73,
      paid: 49,
      consulting: 88,
      revenue: 86,
      assists: 42,
      surfaceIQ: 62,
      socialTS: 63,
      assistRate: 33,
      trustGravity: 41,
      humanHalo: 18,
    },
    recommendedPlayId: "play-soft-cta",
  },
  {
    id: "post-austin-teammate-quote",
    employeeId: "austin",
    text: "The useful framing in Dan's essay: founder-led content is not distribution theater. It is market education with attribution lag.",
    platform: "Teammate Amplification",
    contentType: "Quote Post",
    archetype: "Growth Playmaker",
    campaign: "Founder Narrative",
    ctaType: "Amplification",
    brandTouch: "Every",
    product: "Newsletter",
    launchWindow: true,
    timestamp: "2026-03-28T11:16:00-04:00",
    x: 32,
    y: 18,
    zone: "Teammate Amplification",
    advancedZone: "Teammate quote posts",
    confidence: "Modeled",
    metrics: {
      views: 176000,
      reach: 232000,
      likes: 4400,
      comments: 188,
      replies: 92,
      reposts: 620,
      quotes: 114,
      shares: 740,
      clicks: 1100,
      profileVisits: 3100,
      signups: 142,
      paidSubscriptions: 21,
      consultingLeads: 3,
      revenue: 28000,
      assistedConversions: 228,
    },
    scores: {
      awareness: 76,
      engagement: 71,
      trust: 78,
      clicks: 58,
      signups: 74,
      paid: 62,
      consulting: 48,
      revenue: 53,
      assists: 94,
      surfaceIQ: 83,
      socialTS: 66,
      assistRate: 137,
      trustGravity: 77,
      humanHalo: 61,
    },
    recommendedPlayId: "play-teammate-alley-oop",
  },
  {
    id: "post-dan-category-essay",
    employeeId: "dan",
    text: "The next wave of AI companies will not just sell tools. They will sell new operating rhythms.",
    platform: "Newsletter",
    contentType: "Newsletter Byline",
    archetype: "Founder Engine",
    campaign: "Category Creation",
    ctaType: "Paid subscription",
    brandTouch: "Every",
    product: "Newsletter",
    launchWindow: true,
    timestamp: "2026-03-28T08:00:00-04:00",
    x: 78,
    y: 72,
    zone: "Newsletter",
    advancedZone: "Newsletter bylines",
    confidence: "Direct",
    metrics: {
      views: 284000,
      reach: 324000,
      likes: 9200,
      comments: 620,
      replies: 420,
      reposts: 980,
      quotes: 210,
      shares: 3800,
      clicks: 9200,
      profileVisits: 8400,
      signups: 1620,
      paidSubscriptions: 246,
      consultingLeads: 11,
      revenue: 186000,
      assistedConversions: 480,
    },
    scores: {
      awareness: 86,
      engagement: 82,
      trust: 94,
      clicks: 92,
      signups: 98,
      paid: 96,
      consulting: 84,
      revenue: 94,
      assists: 91,
      surfaceIQ: 94,
      socialTS: 83,
      assistRate: 26,
      trustGravity: 95,
      humanHalo: 72,
    },
    recommendedPlayId: "play-teammate-alley-oop",
  },
  {
    id: "post-dan-x-founder-narrative",
    employeeId: "dan",
    text: "A founder's job is to make the company easier to believe in before it is easy to measure.",
    platform: "X",
    contentType: "Original Post",
    archetype: "Founder Engine",
    campaign: "Founder Narrative",
    ctaType: "No CTA",
    brandTouch: "Personal",
    product: "Brand",
    launchWindow: false,
    timestamp: "2026-04-02T13:45:00-04:00",
    x: 31,
    y: 32,
    zone: "X",
    advancedZone: "Personal AI observations",
    confidence: "Modeled",
    metrics: {
      views: 880000,
      reach: 1040000,
      likes: 28600,
      comments: 920,
      replies: 660,
      reposts: 3400,
      quotes: 820,
      shares: 4100,
      clicks: 2100,
      profileVisits: 18200,
      signups: 322,
      paidSubscriptions: 48,
      consultingLeads: 4,
      revenue: 52000,
      assistedConversions: 520,
    },
    scores: {
      awareness: 96,
      engagement: 88,
      trust: 93,
      clicks: 52,
      signups: 70,
      paid: 66,
      consulting: 42,
      revenue: 58,
      assists: 98,
      surfaceIQ: 90,
      socialTS: 62,
      assistRate: 139,
      trustGravity: 94,
      humanHalo: 91,
    },
    recommendedPlayId: "play-human-halo",
  },
  {
    id: "post-dan-podcast-trust",
    employeeId: "dan",
    text: "Podcast clip: why AI workflows fail when teams automate tasks before they understand taste.",
    platform: "Podcast",
    contentType: "Podcast Clip",
    archetype: "Founder Engine",
    campaign: "Deep Trust",
    ctaType: "Listen",
    brandTouch: "Every",
    product: "Podcast",
    launchWindow: false,
    timestamp: "2026-04-16T12:00:00-04:00",
    x: 52,
    y: 24,
    zone: "YouTube/Podcast",
    advancedZone: "Personal AI observations",
    confidence: "Estimated",
    metrics: {
      views: 132000,
      reach: 156000,
      likes: 3200,
      comments: 210,
      replies: 80,
      reposts: 240,
      quotes: 44,
      shares: 920,
      clicks: 740,
      profileVisits: 2200,
      signups: 118,
      paidSubscriptions: 17,
      consultingLeads: 2,
      revenue: 24000,
      assistedConversions: 190,
    },
    scores: {
      awareness: 69,
      engagement: 75,
      trust: 90,
      clicks: 49,
      signups: 61,
      paid: 56,
      consulting: 38,
      revenue: 44,
      assists: 88,
      surfaceIQ: 81,
      socialTS: 58,
      assistRate: 139,
      trustGravity: 91,
      humanHalo: 87,
    },
    recommendedPlayId: "play-human-halo",
  },
  {
    id: "post-dan-external-founder-repost",
    employeeId: "dan",
    text: "External founder reposted Dan's category essay with a note about how Every explains AI work better than vendors do.",
    platform: "External Amplification",
    contentType: "Quote Post",
    archetype: "Founder Engine",
    campaign: "Category Creation",
    ctaType: "External amplification",
    brandTouch: "Partner",
    product: "Newsletter",
    launchWindow: true,
    timestamp: "2026-03-28T11:18:00-04:00",
    x: 73,
    y: 18,
    zone: "External Amplification",
    advancedZone: "External founder amplification",
    confidence: "Estimated",
    metrics: {
      views: 420000,
      reach: 515000,
      likes: 9800,
      comments: 410,
      replies: 210,
      reposts: 1600,
      quotes: 540,
      shares: 1700,
      clicks: 3300,
      profileVisits: 7100,
      signups: 380,
      paidSubscriptions: 52,
      consultingLeads: 8,
      revenue: 94000,
      assistedConversions: 360,
    },
    scores: {
      awareness: 89,
      engagement: 79,
      trust: 86,
      clicks: 74,
      signups: 82,
      paid: 71,
      consulting: 78,
      revenue: 83,
      assists: 95,
      surfaceIQ: 86,
      socialTS: 69,
      assistRate: 82,
      trustGravity: 84,
      humanHalo: 67,
    },
    recommendedPlayId: "play-launch-rotation",
  },
  {
    id: "post-kieran-product-philosophy",
    employeeId: "kieran",
    text: "Good product taste is often just noticing which parts of the workflow make smart people feel clumsy.",
    platform: "X",
    contentType: "Personal AI Observation",
    archetype: "Builder Philosopher",
    campaign: "Product Craft",
    ctaType: "No CTA",
    brandTouch: "Personal",
    product: "Brand",
    launchWindow: false,
    timestamp: "2026-04-05T17:36:00-04:00",
    x: 20,
    y: 44,
    zone: "X",
    advancedZone: "Personal AI observations",
    confidence: "Modeled",
    metrics: {
      views: 356000,
      reach: 431000,
      likes: 14200,
      comments: 420,
      replies: 260,
      reposts: 1700,
      quotes: 310,
      shares: 1800,
      clicks: 720,
      profileVisits: 6200,
      signups: 112,
      paidSubscriptions: 16,
      consultingLeads: 1,
      revenue: 12000,
      assistedConversions: 242,
    },
    scores: {
      awareness: 84,
      engagement: 92,
      trust: 91,
      clicks: 38,
      signups: 58,
      paid: 51,
      consulting: 24,
      revenue: 32,
      assists: 90,
      surfaceIQ: 87,
      socialTS: 57,
      assistRate: 188,
      trustGravity: 92,
      humanHalo: 94,
    },
    recommendedPlayId: "play-human-halo",
  },
  {
    id: "post-kieran-github-proof",
    employeeId: "kieran",
    text: "Released a small internal eval harness pattern for checking AI workflow quality before demos become promises.",
    platform: "GitHub",
    contentType: "Technical Proof",
    archetype: "Builder Philosopher",
    campaign: "Technical Credibility",
    ctaType: "Repo link",
    brandTouch: "Product",
    product: "AI Workflow",
    launchWindow: false,
    timestamp: "2026-04-10T14:08:00-04:00",
    x: 20,
    y: 72,
    zone: "GitHub",
    advancedZone: "GitHub technical proof",
    confidence: "Direct",
    metrics: {
      views: 46000,
      reach: 62000,
      likes: 680,
      comments: 32,
      replies: 16,
      reposts: 120,
      quotes: 18,
      shares: 210,
      clicks: 1800,
      profileVisits: 1300,
      signups: 76,
      paidSubscriptions: 6,
      consultingLeads: 4,
      revenue: 64000,
      assistedConversions: 54,
    },
    scores: {
      awareness: 47,
      engagement: 55,
      trust: 88,
      clicks: 72,
      signups: 63,
      paid: 46,
      consulting: 74,
      revenue: 80,
      assists: 62,
      surfaceIQ: 84,
      socialTS: 74,
      assistRate: 63,
      trustGravity: 87,
      humanHalo: 36,
    },
    recommendedPlayId: "play-github-linkedin-proof",
  },
  {
    id: "post-kieran-linkedin-design-notes",
    employeeId: "kieran",
    text: "Design note: an AI product earns trust when it shows uncertainty without making the user do extra work.",
    platform: "LinkedIn",
    contentType: "Operator Post",
    archetype: "Builder Philosopher",
    campaign: "Product Craft",
    ctaType: "Soft product CTA",
    brandTouch: "Every",
    product: "AI Workflow",
    launchWindow: false,
    timestamp: "2026-04-15T10:44:00-04:00",
    x: 66,
    y: 49,
    zone: "LinkedIn",
    advancedZone: "LinkedIn operator posts",
    confidence: "Estimated",
    metrics: {
      views: 39000,
      reach: 52000,
      likes: 900,
      comments: 74,
      replies: 20,
      reposts: 66,
      quotes: 11,
      shares: 144,
      clicks: 640,
      profileVisits: 980,
      signups: 58,
      paidSubscriptions: 7,
      consultingLeads: 3,
      revenue: 38000,
      assistedConversions: 42,
    },
    scores: {
      awareness: 42,
      engagement: 68,
      trust: 84,
      clicks: 57,
      signups: 61,
      paid: 45,
      consulting: 67,
      revenue: 72,
      assists: 56,
      surfaceIQ: 79,
      socialTS: 67,
      assistRate: 62,
      trustGravity: 83,
      humanHalo: 71,
    },
    recommendedPlayId: "play-github-linkedin-proof",
  },
  {
    id: "post-kieran-launch-product-diary",
    employeeId: "kieran",
    text: "Product diary from launch week: the most useful thing we shipped was the part that made edge cases visible.",
    platform: "Launches",
    contentType: "Launch Post",
    archetype: "Builder Philosopher",
    campaign: "Launch Week",
    ctaType: "Product link",
    brandTouch: "Product",
    product: "AI Workflow",
    launchWindow: true,
    timestamp: "2026-03-29T16:30:00-04:00",
    x: 48,
    y: 55,
    zone: "Launches",
    advancedZone: "Launch windows",
    confidence: "Modeled",
    metrics: {
      views: 118000,
      reach: 148000,
      likes: 3100,
      comments: 120,
      replies: 80,
      reposts: 420,
      quotes: 92,
      shares: 520,
      clicks: 1500,
      profileVisits: 2500,
      signups: 210,
      paidSubscriptions: 24,
      consultingLeads: 3,
      revenue: 36000,
      assistedConversions: 180,
    },
    scores: {
      awareness: 70,
      engagement: 73,
      trust: 86,
      clicks: 66,
      signups: 80,
      paid: 65,
      consulting: 48,
      revenue: 58,
      assists: 86,
      surfaceIQ: 82,
      socialTS: 70,
      assistRate: 76,
      trustGravity: 88,
      humanHalo: 80,
    },
    recommendedPlayId: "play-launch-rotation",
  },
];

export const rippleEvents: RippleEvent[] = [
  {
    id: "ripple-1",
    rootPostId: "post-austin-ai-consulting",
    employeeId: "austin",
    actor: "Austin Tedesco",
    platform: "X",
    eventType: "Root Post",
    timestamp: "2026-04-09T10:02:00-04:00",
    value: 0,
    confidence: "Direct",
  },
  {
    id: "ripple-2",
    rootPostId: "post-austin-ai-consulting",
    parentId: "ripple-1",
    actor: "Teammate",
    platform: "Teammate Amplification",
    eventType: "Quote Post",
    timestamp: "2026-04-09T10:11:00-04:00",
    value: 42,
    confidence: "Modeled",
  },
  {
    id: "ripple-3",
    rootPostId: "post-austin-ai-consulting",
    parentId: "ripple-2",
    actor: "External founder",
    platform: "External Amplification",
    eventType: "Repost",
    timestamp: "2026-04-09T10:18:00-04:00",
    value: 86,
    confidence: "Estimated",
  },
  {
    id: "ripple-4",
    rootPostId: "post-austin-ai-consulting",
    parentId: "ripple-3",
    actor: "High-intent operators",
    platform: "X",
    eventType: "Replies",
    timestamp: "2026-04-09T10:34:00-04:00",
    value: 128,
    confidence: "Estimated",
  },
  {
    id: "ripple-5",
    rootPostId: "post-austin-ai-consulting",
    parentId: "ripple-4",
    actor: "Known prospects",
    platform: "X",
    eventType: "Profile Visits",
    timestamp: "2026-04-09T11:20:00-04:00",
    value: 420,
    confidence: "Needs Internal Analytics",
  },
  {
    id: "ripple-6",
    rootPostId: "post-austin-ai-consulting",
    parentId: "ripple-5",
    actor: "Site visitors",
    platform: "Newsletter",
    eventType: "Site Clicks",
    timestamp: "2026-04-09T12:05:00-04:00",
    value: 3800,
    confidence: "Needs Internal Analytics",
  },
  {
    id: "ripple-7",
    rootPostId: "post-austin-ai-consulting",
    parentId: "ripple-6",
    actor: "New readers",
    platform: "Newsletter",
    eventType: "Newsletter Signups",
    timestamp: "2026-04-09T12:32:00-04:00",
    value: 486,
    confidence: "Needs Internal Analytics",
  },
  {
    id: "ripple-8",
    rootPostId: "post-austin-ai-consulting",
    parentId: "ripple-7",
    actor: "Subscribers",
    platform: "Newsletter",
    eventType: "Paid Subscription",
    timestamp: "2026-04-11T09:02:00-04:00",
    value: 42,
    confidence: "Needs Internal Analytics",
  },
  {
    id: "ripple-9",
    rootPostId: "post-austin-ai-consulting",
    parentId: "ripple-8",
    actor: "Pipeline",
    platform: "LinkedIn",
    eventType: "Consulting Inquiry",
    timestamp: "2026-04-20T13:42:00-04:00",
    value: 9,
    confidence: "Needs Internal Analytics",
  },
  {
    id: "ripple-10",
    rootPostId: "post-dan-category-essay",
    employeeId: "dan",
    actor: "Dan Shipper",
    platform: "Newsletter",
    eventType: "Root Essay",
    timestamp: "2026-03-28T08:00:00-04:00",
    value: 0,
    confidence: "Direct",
  },
  {
    id: "ripple-11",
    rootPostId: "post-dan-category-essay",
    parentId: "ripple-10",
    actor: "Austin Tedesco",
    platform: "Teammate Amplification",
    eventType: "Teammate Quote",
    timestamp: "2026-03-28T11:16:00-04:00",
    value: 228,
    confidence: "Modeled",
  },
  {
    id: "ripple-12",
    rootPostId: "post-dan-category-essay",
    parentId: "ripple-10",
    actor: "External founder",
    platform: "External Amplification",
    eventType: "Founder Repost",
    timestamp: "2026-03-28T11:18:00-04:00",
    value: 360,
    confidence: "Estimated",
  },
  {
    id: "ripple-13",
    rootPostId: "post-dan-category-essay",
    parentId: "ripple-12",
    actor: "New Every readers",
    platform: "Newsletter",
    eventType: "Paid Subscription",
    timestamp: "2026-03-30T09:14:00-04:00",
    value: 246,
    confidence: "Direct",
  },
];

export const experiments: Experiment[] = [
  {
    id: "exp-newsletter-bridge",
    playId: "play-newsletter-bridge",
    name: "Austin weekly newsletter bridge",
    hypothesis: "A social thread with a newsletter-specific promise will raise signup conversion without lowering trust.",
    ownerEmployeeId: "austin",
    status: "Planned",
    metric: "Signups",
  },
  {
    id: "exp-github-proof",
    playId: "play-github-linkedin-proof",
    name: "Kieran technical proof translation",
    hypothesis: "Translating GitHub proof into LinkedIn operator language increases consulting intent.",
    ownerEmployeeId: "kieran",
    status: "Running",
    metric: "Consulting Leads",
  },
];

export const dataSources: DataSource[] = [
  {
    id: "source-public",
    name: "Public Surface Data",
    category: "Public Surface Data",
    readiness: "Ready",
    confidence: "Estimated",
    description: "Visible post metadata, public engagement, reposts, replies, and surface-level diffusion.",
  },
  {
    id: "source-auth",
    name: "Authenticated Platform Data",
    category: "Authenticated Platform Data",
    readiness: "Needs OAuth",
    confidence: "Direct",
    description: "Private impressions, profile visits, detailed audience splits, and verified click events.",
  },
  {
    id: "source-internal",
    name: "Internal Analytics",
    category: "Internal Analytics",
    readiness: "Future",
    confidence: "Needs Internal Analytics",
    description: "Newsletter analytics, Stripe, CRM, UTM shortener, web analytics, and revenue attribution.",
  },
  {
    id: "source-modeled",
    name: "Modeled Intelligence",
    category: "Modeled Intelligence",
    readiness: "Manual Import",
    confidence: "Modeled",
    description: "Assisted conversion estimates, trust gravity, hockey assists, and diffusion path inference.",
  },
  {
    id: "source-x-api",
    name: "X API",
    category: "Authenticated Platform Data",
    readiness: "Needs OAuth",
    confidence: "Direct",
    description: "Impressions, engagements, replies, reposts, quote posts, and profile-click estimates.",
  },
  {
    id: "source-linkedin",
    name: "LinkedIn API / Manual Import",
    category: "Authenticated Platform Data",
    readiness: "Manual Import",
    confidence: "Direct",
    description: "B2B intent, profile visits, company engagement, lead comments, and consulting signals.",
  },
  {
    id: "source-github",
    name: "GitHub API",
    category: "Public Surface Data",
    readiness: "Ready",
    confidence: "Direct",
    description: "Stars, forks, contributors, issues, repo traffic where available, and technical credibility signals.",
  },
  {
    id: "source-instagram",
    name: "Instagram Graph API",
    category: "Authenticated Platform Data",
    readiness: "Needs OAuth",
    confidence: "Direct",
    description: "Human affinity, reach, saves, shares, and follower profile signals.",
  },
  {
    id: "source-newsletter",
    name: "Newsletter Platform",
    category: "Internal Analytics",
    readiness: "Future",
    confidence: "Direct",
    description: "Opens, clicks, signups, paid conversions, source tags, and subscriber cohorts.",
  },
  {
    id: "source-stripe",
    name: "Stripe",
    category: "Internal Analytics",
    readiness: "Future",
    confidence: "Direct",
    description: "Paid subscriptions, revenue, customer cohorts, and subscription expansion.",
  },
  {
    id: "source-crm",
    name: "CRM",
    category: "Internal Analytics",
    readiness: "Future",
    confidence: "Direct",
    description: "Consulting leads, opportunity stage, deal value, and closed revenue.",
  },
  {
    id: "source-web",
    name: "Web Analytics",
    category: "Internal Analytics",
    readiness: "Future",
    confidence: "Direct",
    description: "Landing-page paths, UTMs, referrers, sessions, and conversion funnels.",
  },
  {
    id: "source-utm",
    name: "UTM Shortener",
    category: "Internal Analytics",
    readiness: "Future",
    confidence: "Direct",
    description: "Per-post tracked links for attribution across platforms and campaigns.",
  },
];

export const employeeById = Object.fromEntries(employees.map((employee) => [employee.id, employee]));
export const playById = Object.fromEntries(plays.map((play) => [play.id, play]));
