// /lib/data/coverageMatrix.ts
// Real researched seed data — Surface coverage matrix

export type MatrixCell = "verified" | "likely" | "absent";

export interface CoverageRow {
  entityId: string;
  entityName: string;
  entityType: "company" | "employee";
  role?: string;
  archetype?: string;
  surfaces: Record<string, MatrixCell>;
  verifiedCount: number;
  likelyCount: number;
  absentCount: number;
  coverageScore: number;
}

export const coverageMatrix: CoverageRow[] = [
  {
    entityId: "comp_every_001",
    entityName: "Every",
    entityType: "company",
    surfaces: {
      x: "verified",
      linkedin: "verified",
      github: "likely",
      substack: "verified",
      youtube: "absent",
      instagram: "absent",
      tiktok: "absent",
      product_hunt: "verified",
      personal_site: "verified",
      podcast: "verified",
      book: "absent",
      external_interview: "absent",
    },
    verifiedCount: 7,
    likelyCount: 1,
    absentCount: 3,
    coverageScore: 55,
  },
  {
    entityId: "emp_001",
    entityName: "Dan Shipper",
    entityType: "employee",
    role: "CEO & Co-Founder",
    archetype: "Founder Engine",
    surfaces: {
      x: "verified",
      linkedin: "verified",
      github: "likely",
      substack: "verified",
      youtube: "absent",
      instagram: "absent",
      tiktok: "absent",
      product_hunt: "verified",
      personal_site: "verified",
      podcast: "verified",
      book: "absent",
      external_interview: "absent",
    },
    verifiedCount: 6,
    likelyCount: 1,
    absentCount: 5,
    coverageScore: 78,
  },
  {
    entityId: "emp_002",
    entityName: "Austin Tedesco",
    entityType: "employee",
    role: "Head of Growth",
    archetype: "Growth Playmaker",
    surfaces: {
      x: "verified",
      linkedin: "verified",
      github: "absent",
      substack: "verified",
      youtube: "absent",
      instagram: "absent",
      tiktok: "absent",
      product_hunt: "absent",
      personal_site: "absent",
      podcast: "absent",
      book: "absent",
      external_interview: "absent",
    },
    verifiedCount: 3,
    likelyCount: 0,
    absentCount: 9,
    coverageScore: 71,
  },
  {
    entityId: "emp_003",
    entityName: "Brandon Gell",
    entityType: "employee",
    role: "Product Manager / GM",
    archetype: "Trust Builder",
    surfaces: {
      x: "verified",
      linkedin: "verified",
      github: "absent",
      substack: "absent",
      youtube: "absent",
      instagram: "absent",
      tiktok: "absent",
      product_hunt: "verified",
      personal_site: "absent",
      podcast: "absent",
      book: "absent",
      external_interview: "absent",
    },
    verifiedCount: 3,
    likelyCount: 0,
    absentCount: 9,
    coverageScore: 52,
  },
  {
    entityId: "emp_004",
    entityName: "Kate Lee",
    entityType: "employee",
    role: "Editorial Lead",
    archetype: "Authority Anchor",
    surfaces: {
      x: "verified",
      linkedin: "verified",
      github: "absent",
      substack: "verified",
      youtube: "absent",
      instagram: "absent",
      tiktok: "absent",
      product_hunt: "absent",
      personal_site: "absent",
      podcast: "absent",
      book: "absent",
      external_interview: "absent",
    },
    verifiedCount: 3,
    likelyCount: 0,
    absentCount: 9,
    coverageScore: 61,
  },
  {
    entityId: "emp_005",
    entityName: "Kieran Klaassen",
    entityType: "employee",
    role: "Engineering Lead / Builder",
    archetype: "Builder Philosopher",
    surfaces: {
      x: "verified",
      linkedin: "verified",
      github: "verified",
      substack: "absent",
      youtube: "absent",
      instagram: "absent",
      tiktok: "absent",
      product_hunt: "verified",
      personal_site: "verified",
      podcast: "verified",
      book: "absent",
      external_interview: "absent",
    },
    verifiedCount: 6,
    likelyCount: 0,
    absentCount: 6,
    coverageScore: 65,
  },
  {
    entityId: "emp_006",
    entityName: "Yash Poojary",
    entityType: "employee",
    role: "Growth Engineer",
    archetype: "Surface Specialist",
    surfaces: {
      x: "verified",
      linkedin: "verified",
      github: "absent",
      substack: "absent",
      youtube: "absent",
      instagram: "absent",
      tiktok: "absent",
      product_hunt: "absent",
      personal_site: "absent",
      podcast: "absent",
      book: "absent",
      external_interview: "absent",
    },
    verifiedCount: 2,
    likelyCount: 0,
    absentCount: 10,
    coverageScore: 48,
  },
  {
    entityId: "emp_007",
    entityName: "Naveen Naidu",
    entityType: "employee",
    role: "Engineer / Product",
    archetype: "Human Halo",
    surfaces: {
      x: "verified",
      linkedin: "verified",
      github: "absent",
      substack: "absent",
      youtube: "absent",
      instagram: "absent",
      tiktok: "absent",
      product_hunt: "absent",
      personal_site: "absent",
      podcast: "absent",
      book: "absent",
      external_interview: "absent",
    },
    verifiedCount: 2,
    likelyCount: 0,
    absentCount: 10,
    coverageScore: 45,
  },
  {
    entityId: "emp_008",
    entityName: "Natalia Quintero",
    entityType: "employee",
    role: "Enterprise / Consulting Lead",
    archetype: "Closer",
    surfaces: {
      x: "verified",
      linkedin: "verified",
      github: "absent",
      substack: "absent",
      youtube: "absent",
      instagram: "absent",
      tiktok: "absent",
      product_hunt: "absent",
      personal_site: "absent",
      podcast: "absent",
      book: "absent",
      external_interview: "absent",
    },
    verifiedCount: 2,
    likelyCount: 0,
    absentCount: 10,
    coverageScore: 54,
  },
  {
    entityId: "emp_009",
    entityName: "Katie Parrott",
    entityType: "employee",
    role: "Writer / Editor",
    archetype: "Trust Builder",
    surfaces: {
      x: "verified",
      linkedin: "verified",
      github: "absent",
      substack: "verified",
      youtube: "absent",
      instagram: "absent",
      tiktok: "absent",
      product_hunt: "absent",
      personal_site: "absent",
      podcast: "absent",
      book: "absent",
      external_interview: "absent",
    },
    verifiedCount: 3,
    likelyCount: 0,
    absentCount: 9,
    coverageScore: 52,
  },
  {
    entityId: "emp_010",
    entityName: "Laura Entis",
    entityType: "employee",
    role: "Writer / Reporter",
    archetype: "Launch Sixth Man",
    surfaces: {
      x: "absent",
      linkedin: "verified",
      github: "absent",
      substack: "absent",
      youtube: "absent",
      instagram: "absent",
      tiktok: "absent",
      product_hunt: "absent",
      personal_site: "absent",
      podcast: "absent",
      book: "absent",
      external_interview: "absent",
    },
    verifiedCount: 1,
    likelyCount: 0,
    absentCount: 11,
    coverageScore: 44,
  },
  {
    entityId: "emp_011",
    entityName: "Willie Williams",
    entityType: "employee",
    role: "Operations / Finance",
    archetype: "Human Halo",
    surfaces: {
      x: "absent",
      linkedin: "verified",
      github: "absent",
      substack: "absent",
      youtube: "absent",
      instagram: "absent",
      tiktok: "absent",
      product_hunt: "absent",
      personal_site: "absent",
      podcast: "absent",
      book: "absent",
      external_interview: "absent",
    },
    verifiedCount: 1,
    likelyCount: 0,
    absentCount: 11,
    coverageScore: 32,
  },
  {
    entityId: "emp_012",
    entityName: "Lucas Crespo",
    entityType: "employee",
    role: "Designer",
    archetype: "Surface Specialist",
    surfaces: {
      x: "verified",
      linkedin: "verified",
      github: "absent",
      substack: "absent",
      youtube: "absent",
      instagram: "absent",
      tiktok: "absent",
      product_hunt: "absent",
      personal_site: "absent",
      podcast: "absent",
      book: "absent",
      external_interview: "verified",
    },
    verifiedCount: 3,
    likelyCount: 0,
    absentCount: 9,
    coverageScore: 41,
  },
  {
    entityId: "emp_013",
    entityName: "Mike Taylor",
    entityType: "employee",
    role: "Engineer / Author",
    archetype: "Authority Anchor",
    surfaces: {
      x: "verified",
      linkedin: "verified",
      github: "verified",
      substack: "absent",
      youtube: "absent",
      instagram: "absent",
      tiktok: "absent",
      product_hunt: "absent",
      personal_site: "absent",
      podcast: "absent",
      book: "verified",
      external_interview: "absent",
    },
    verifiedCount: 4,
    likelyCount: 0,
    absentCount: 8,
    coverageScore: 58,
  },
  {
    entityId: "emp_014",
    entityName: "Alex Duffy",
    entityType: "employee",
    role: "Engineer",
    archetype: "Builder Philosopher",
    surfaces: {
      x: "verified",
      linkedin: "verified",
      github: "verified",
      substack: "absent",
      youtube: "absent",
      instagram: "absent",
      tiktok: "absent",
      product_hunt: "absent",
      personal_site: "absent",
      podcast: "absent",
      book: "absent",
      external_interview: "absent",
    },
    verifiedCount: 3,
    likelyCount: 0,
    absentCount: 9,
    coverageScore: 38,
  },
  {
    entityId: "emp_015",
    entityName: "Rhea Purohit",
    entityType: "employee",
    role: "Growth / Marketing",
    archetype: "Launch Sixth Man",
    surfaces: {
      x: "verified",
      linkedin: "verified",
      github: "absent",
      substack: "absent",
      youtube: "absent",
      instagram: "absent",
      tiktok: "absent",
      product_hunt: "absent",
      personal_site: "verified",
      podcast: "absent",
      book: "absent",
      external_interview: "absent",
    },
    verifiedCount: 3,
    likelyCount: 0,
    absentCount: 9,
    coverageScore: 42,
  },
  {
    entityId: "emp_016",
    entityName: "Anthony Scarpulla",
    entityType: "employee",
    role: "Engineer",
    archetype: "Builder Philosopher",
    surfaces: {
      x: "absent",
      linkedin: "absent",
      github: "absent",
      substack: "absent",
      youtube: "absent",
      instagram: "absent",
      tiktok: "absent",
      product_hunt: "absent",
      personal_site: "absent",
      podcast: "absent",
      book: "absent",
      external_interview: "absent",
    },
    verifiedCount: 0,
    likelyCount: 0,
    absentCount: 12,
    coverageScore: 18,
  },
];
