// /lib/data/dynamicDuos.ts
// Real researched seed data — Team chemistry and dynamic duos

export interface DynamicDuo {
  id: string;
  playerAId: string;
  playerAName: string;
  playerBId: string;
  playerBName: string;
  synergyName: string;
  chemistryScore: number;
  effect: string;
}

export const dynamicDuos: DynamicDuo[] = [
  {
    id: "duo_001",
    playerAId: "emp_001",
    playerAName: "Dan Shipper",
    playerBId: "emp_002",
    playerBName: "Austin Tedesco",
    synergyName: "Founder-Growth Engine",
    chemistryScore: 94,
    effect: "Dan narrative + Austin conversion = +15% Trust Gravity on launch days",
  },
  {
    id: "duo_002",
    playerAId: "emp_001",
    playerAName: "Dan Shipper",
    playerBId: "emp_005",
    playerBName: "Kieran Klaassen",
    synergyName: "Builder-Philosopher Stack",
    chemistryScore: 82,
    effect: "Dan's vision + Kieran's conviction = product-market clarity",
  },
  {
    id: "duo_003",
    playerAId: "emp_002",
    playerAName: "Austin Tedesco",
    playerBId: "emp_005",
    playerBName: "Kieran Klaassen",
    synergyName: "Growth-Builder Pipeline",
    chemistryScore: 87,
    effect: "Austin's CTAs + Kieran's conviction = highest trial conversion rate",
  },
  {
    id: "duo_004",
    playerAId: "emp_003",
    playerAName: "Brandon Gell",
    playerBId: "emp_005",
    playerBName: "Kieran Klaassen",
    synergyName: "Product-Builder Trust",
    chemistryScore: 79,
    effect: "Brandon's authenticity + Kieran's conviction = Cora's best trust signal",
  },
  {
    id: "duo_005",
    playerAId: "emp_004",
    playerAName: "Kate Lee",
    playerBId: "emp_001",
    playerBName: "Dan Shipper",
    synergyName: "Founder-Editorial Narrative",
    chemistryScore: 85,
    effect: "Dan's vision + Kate's editorial rigor = Every's voice",
  },
  {
    id: "duo_006",
    playerAId: "emp_006",
    playerAName: "Yash Poojary",
    playerBId: "emp_002",
    playerBName: "Austin Tedesco",
    synergyName: "Growth Experiment Duo",
    chemistryScore: 83,
    effect: "Yash's experiments + Austin's strategy = rapid iteration cycle",
  },
  {
    id: "duo_007",
    playerAId: "emp_007",
    playerAName: "Naveen Naidu",
    playerBId: "emp_005",
    playerBName: "Kieran Klaassen",
    synergyName: "Builder-Culture Stack",
    chemistryScore: 76,
    effect: "Naveen's cultural trust + Kieran's technical depth = Cora's human face",
  },
  {
    id: "duo_008",
    playerAId: "emp_008",
    playerAName: "Natalia Quintero",
    playerBId: "emp_013",
    playerBName: "Mike Taylor",
    synergyName: "Enterprise Authority Duo",
    chemistryScore: 88,
    effect: "Natalia's consulting + Mike's O'Reilly authority = enterprise demand generation",
  },
  {
    id: "duo_009",
    playerAId: "emp_009",
    playerAName: "Katie Parrott",
    playerBId: "emp_004",
    playerBName: "Kate Lee",
    synergyName: "Editorial Clarity Duo",
    chemistryScore: 86,
    effect: "Katie's accessibility + Kate's authority = Every's editorial range",
  },
  {
    id: "duo_010",
    playerAId: "emp_010",
    playerAName: "Laura Entis",
    playerBId: "emp_004",
    playerBName: "Kate Lee",
    synergyName: "Editorial Launch Duo",
    chemistryScore: 78,
    effect: "Laura's launch speed + Kate's editorial rigor = rapid high-quality content",
  },
  {
    id: "duo_011",
    playerAId: "emp_011",
    playerAName: "Willie Williams",
    playerBId: "emp_001",
    playerBName: "Dan Shipper",
    synergyName: "Founder-Ops Stability",
    chemistryScore: 70,
    effect: "Willie's operational stability + Dan's vision = sustainable growth",
  },
  {
    id: "duo_012",
    playerAId: "emp_012",
    playerAName: "Lucas Crespo",
    playerBId: "emp_001",
    playerBName: "Dan Shipper",
    synergyName: "Design-Brand Trust",
    chemistryScore: 74,
    effect: "Lucas's design authority + Every brand = visual trust signal",
  },
  {
    id: "duo_013",
    playerAId: "emp_013",
    playerAName: "Mike Taylor",
    playerBId: "emp_001",
    playerBName: "Dan Shipper",
    synergyName: "Founder-Authority Stack",
    chemistryScore: 84,
    effect: "Mike's technical depth + Dan's narrative = authoritative founder stories",
  },
  {
    id: "duo_014",
    playerAId: "emp_014",
    playerAName: "Alex Duffy",
    playerBId: "emp_005",
    playerBName: "Kieran Klaassen",
    synergyName: "Engineering Depth Stack",
    chemistryScore: 75,
    effect: "Alex's practical depth + Kieran's conviction = complete technical picture",
  },
  {
    id: "duo_015",
    playerAId: "emp_015",
    playerAName: "Rhea Purohit",
    playerBId: "emp_002",
    playerBName: "Austin Tedesco",
    synergyName: "Growth Execution Duo",
    chemistryScore: 80,
    effect: "Rhea's launch speed + Austin's strategy = rapid experiment iteration",
  },
  {
    id: "duo_016",
    playerAId: "emp_016",
    playerAName: "Anthony Scarpulla",
    playerBId: "emp_005",
    playerBName: "Kieran Klaassen",
    synergyName: "Engineering Pair",
    chemistryScore: 65,
    effect: "Anthony's quiet build + Kieran's public conviction = balanced engineering presence",
  },
];
