// /lib/data/employees.ts
// Real researched seed data — 16 public-facing employees

export type Archetype =
  | "Founder Engine"
  | "Growth Playmaker"
  | "Builder Philosopher"
  | "Trust Builder"
  | "Launch Sixth Man"
  | "Closer"
  | "Human Halo"
  | "Authority Anchor"
  | "Surface Specialist";

export interface BadgeSet {
  gold: string[];
  silver: string[];
  bronze: string[];
  hof: string[];
}

export interface ShotDistribution {
  promo: number;
  philosophy: number;
  personal: number;
  assists: number;
  setup: number;
}

export interface EfficiencyMetrics {
  socialTS: number;
  socialEFG: number;
  assistRate: number;
  reboundRate: number;
  turnoverRate: number;
}

export interface Employee {
  id: string;
  name: string;
  role: string;
  archetype: Archetype;
  archetypeDescription: string;
  department: string;
  isGM: boolean;
  productLine: string;
  surfaceIQ: number;
  coverageScore: number;
  trustGravity: number;
  assistCredit: number;
  shotSelection: number;
  signatureMove: string;
  badges: BadgeSet;
  shotDistribution: ShotDistribution;
  efficiency: EfficiencyMetrics;
  takeoverLevel: number;
  takeoverSurface: string | null;
}

export const employees: Employee[] = [
  {
    id: "emp_001",
    name: "Dan Shipper",
    role: "CEO & Co-Founder",
    archetype: "Founder Engine",
    archetypeDescription: "Dual threat: can score (narrative) and facilitate (team). Drives the offense.",
    department: "Leadership",
    isGM: true,
    productLine: "Every (company)",
    surfaceIQ: 91,
    coverageScore: 78,
    trustGravity: 88,
    assistCredit: 72,
    shotSelection: 85,
    signatureMove: "The Founder Thread — long-form narrative that converts readers to believers",
    badges: {
      gold: ["X Authority", "Substack Dominance", "Founder Narrative"],
      silver: ["LinkedIn Presence", "Podcast Guest"],
      bronze: ["GitHub Visibility"],
      hof: ["Newsletter Mastery"],
    },
    shotDistribution: {
      promo: 0.12,
      philosophy: 0.35,
      personal: 0.28,
      assists: 0.15,
      setup: 0.1,
    },
    efficiency: {
      socialTS: 0.142,
      socialEFG: 0.168,
      assistRate: 0.152,
      reboundRate: 0.08,
      turnoverRate: 0.03,
    },
    takeoverLevel: 4,
    takeoverSurface: "substack",
  },
  {
    id: "emp_002",
    name: "Austin Tedesco",
    role: "Head of Growth",
    archetype: "Growth Playmaker",
    archetypeDescription: "High pass accuracy, creates for others, converts off assists. The floor general.",
    department: "Growth",
    isGM: true,
    productLine: "Every (company)",
    surfaceIQ: 84,
    coverageScore: 71,
    trustGravity: 79,
    assistCredit: 91,
    shotSelection: 88,
    signatureMove: "The Conversion Thread — efficient volume with surgical CTAs",
    badges: {
      gold: ["X Efficiency", "Assist King", "Launch Coordinator"],
      silver: ["LinkedIn Growth", "Experiment Design"],
      bronze: ["Newsletter Cross-Promo"],
      hof: [],
    },
    shotDistribution: {
      promo: 0.09,
      philosophy: 0.27,
      personal: 0.4,
      assists: 0.18,
      setup: 0.06,
    },
    efficiency: {
      socialTS: 0.112,
      socialEFG: 0.134,
      assistRate: 0.178,
      reboundRate: 0.06,
      turnoverRate: 0.04,
    },
    takeoverLevel: 3,
    takeoverSurface: "x",
  },
  {
    id: "emp_003",
    name: "Brandon Gell",
    role: "Product Manager / GM",
    archetype: "Trust Builder",
    archetypeDescription: "Protects brand reputation, high interior presence. The defensive anchor.",
    department: "Product",
    isGM: true,
    productLine: "Cora",
    surfaceIQ: 68,
    coverageScore: 52,
    trustGravity: 76,
    assistCredit: 58,
    shotSelection: 71,
    signatureMove: "The Authentic Post — unpolished, high-trust content that converts through honesty",
    badges: {
      gold: ["Authenticity", "Community Trust"],
      silver: ["X Presence", "Product Storytelling"],
      bronze: ["LinkedIn"],
      hof: [],
    },
    shotDistribution: {
      promo: 0.15,
      philosophy: 0.2,
      personal: 0.45,
      assists: 0.12,
      setup: 0.08,
    },
    efficiency: {
      socialTS: 0.095,
      socialEFG: 0.112,
      assistRate: 0.12,
      reboundRate: 0.07,
      turnoverRate: 0.05,
    },
    takeoverLevel: 2,
    takeoverSurface: "x",
  },
  {
    id: "emp_004",
    name: "Kate Lee",
    role: "Editorial Lead",
    archetype: "Authority Anchor",
    archetypeDescription: "Dominates specific authority surfaces. The post powerhouse.",
    department: "Editorial",
    isGM: false,
    productLine: "Every (content)",
    surfaceIQ: 75,
    coverageScore: 61,
    trustGravity: 82,
    assistCredit: 68,
    shotSelection: 79,
    signatureMove: "The Editorial Thread — long-form analysis that establishes topical authority",
    badges: {
      gold: ["Editorial Authority", "Substack Quality"],
      silver: ["X Presence", "LinkedIn"],
      bronze: [],
      hof: [],
    },
    shotDistribution: {
      promo: 0.18,
      philosophy: 0.42,
      personal: 0.22,
      assists: 0.12,
      setup: 0.06,
    },
    efficiency: {
      socialTS: 0.108,
      socialEFG: 0.125,
      assistRate: 0.12,
      reboundRate: 0.09,
      turnoverRate: 0.03,
    },
    takeoverLevel: 2,
    takeoverSurface: "substack",
  },
  {
    id: "emp_005",
    name: "Kieran Klaassen",
    role: "Engineering Lead / Builder",
    archetype: "Builder Philosopher",
    archetypeDescription: "Rare combo: technical depth + public communication range. The 2-way stretch five.",
    department: "Engineering",
    isGM: true,
    productLine: "Cora",
    surfaceIQ: 79,
    coverageScore: 65,
    trustGravity: 74,
    assistCredit: 81,
    shotSelection: 76,
    signatureMove: "The Conviction Tweet — technical depth with unshakeable product belief",
    badges: {
      gold: ["GitHub Visibility", "X Conviction", "Technical Authority"],
      silver: ["LinkedIn", "Personal Product Site"],
      bronze: ["Podcast Guest"],
      hof: [],
    },
    shotDistribution: {
      promo: 0.08,
      philosophy: 0.55,
      personal: 0.22,
      assists: 0.1,
      setup: 0.05,
    },
    efficiency: {
      socialTS: 0.095,
      socialEFG: 0.098,
      assistRate: 0.1,
      reboundRate: 0.11,
      turnoverRate: 0.02,
    },
    takeoverLevel: 3,
    takeoverSurface: "x",
  },
  {
    id: "emp_006",
    name: "Yash Poojary",
    role: "Growth Engineer",
    archetype: "Surface Specialist",
    archetypeDescription: "Elite at one surface type, average elsewhere. The 3-level scorer.",
    department: "Growth",
    isGM: false,
    productLine: "Every (growth systems)",
    surfaceIQ: 71,
    coverageScore: 48,
    trustGravity: 65,
    assistCredit: 72,
    shotSelection: 68,
    signatureMove: "The Promo Pivot — personality-driven growth content that doesn't feel like marketing",
    badges: {
      gold: ["X Personality", "Growth Experimentation"],
      silver: ["LinkedIn"],
      bronze: [],
      hof: [],
    },
    shotDistribution: {
      promo: 0.22,
      philosophy: 0.25,
      personal: 0.35,
      assists: 0.12,
      setup: 0.06,
    },
    efficiency: {
      socialTS: 0.088,
      socialEFG: 0.102,
      assistRate: 0.12,
      reboundRate: 0.06,
      turnoverRate: 0.06,
    },
    takeoverLevel: 2,
    takeoverSurface: "x",
  },
  {
    id: "emp_007",
    name: "Naveen Naidu",
    role: "Engineer / Product",
    archetype: "Human Halo",
    archetypeDescription: "Boosts teammates' performance by presence alone. The floor general.",
    department: "Engineering",
    isGM: false,
    productLine: "Cora",
    surfaceIQ: 66,
    coverageScore: 45,
    trustGravity: 71,
    assistCredit: 65,
    shotSelection: 62,
    signatureMove: "The Cultural Post — product-adjacent humanity that builds trust without asking",
    badges: {
      gold: ["Cultural Trust", "X Authenticity"],
      silver: ["LinkedIn"],
      bronze: [],
      hof: [],
    },
    shotDistribution: {
      promo: 0.05,
      philosophy: 0.18,
      personal: 0.55,
      assists: 0.15,
      setup: 0.07,
    },
    efficiency: {
      socialTS: 0.082,
      socialEFG: 0.095,
      assistRate: 0.15,
      reboundRate: 0.08,
      turnoverRate: 0.04,
    },
    takeoverLevel: 2,
    takeoverSurface: "x",
  },
  {
    id: "emp_008",
    name: "Natalia Quintero",
    role: "Enterprise / Consulting Lead",
    archetype: "Closer",
    archetypeDescription: "Peaks under pressure; late-game situations. The clutch gene.",
    department: "Sales",
    isGM: false,
    productLine: "Every (enterprise)",
    surfaceIQ: 72,
    coverageScore: 54,
    trustGravity: 80,
    assistCredit: 58,
    shotSelection: 83,
    signatureMove: "The LinkedIn Close — enterprise insight that converts comments to consulting leads",
    badges: {
      gold: ["LinkedIn Enterprise", "Consulting Authority"],
      silver: ["X Presence"],
      bronze: [],
      hof: [],
    },
    shotDistribution: {
      promo: 0.2,
      philosophy: 0.3,
      personal: 0.25,
      assists: 0.15,
      setup: 0.1,
    },
    efficiency: {
      socialTS: 0.105,
      socialEFG: 0.122,
      assistRate: 0.15,
      reboundRate: 0.1,
      turnoverRate: 0.04,
    },
    takeoverLevel: 3,
    takeoverSurface: "linkedin",
  },
  {
    id: "emp_009",
    name: "Katie Parrott",
    role: "Writer / Editor",
    archetype: "Trust Builder",
    archetypeDescription: "Protects brand reputation, high interior presence. The defensive anchor.",
    department: "Editorial",
    isGM: false,
    productLine: "Every (content)",
    surfaceIQ: 70,
    coverageScore: 52,
    trustGravity: 75,
    assistCredit: 62,
    shotSelection: 74,
    signatureMove: "The Clarifying Thread — complex topics made accessible through patient explanation",
    badges: {
      gold: ["Editorial Clarity", "X Engagement"],
      silver: ["LinkedIn", "Substack"],
      bronze: [],
      hof: [],
    },
    shotDistribution: {
      promo: 0.14,
      philosophy: 0.38,
      personal: 0.28,
      assists: 0.14,
      setup: 0.06,
    },
    efficiency: {
      socialTS: 0.098,
      socialEFG: 0.115,
      assistRate: 0.14,
      reboundRate: 0.08,
      turnoverRate: 0.03,
    },
    takeoverLevel: 2,
    takeoverSurface: "x",
  },
  {
    id: "emp_010",
    name: "Laura Entis",
    role: "Writer / Reporter",
    archetype: "Launch Sixth Man",
    archetypeDescription: "Comes off bench cold, heats up fast for specific launches. The microwave.",
    department: "Editorial",
    isGM: false,
    productLine: "Every (content)",
    surfaceIQ: 64,
    coverageScore: 44,
    trustGravity: 68,
    assistCredit: 55,
    shotSelection: 70,
    signatureMove: "The Launch Heat — rapid, high-quality content that spikes during product moments",
    badges: {
      gold: ["Launch Speed", "X Quality"],
      silver: ["LinkedIn"],
      bronze: [],
      hof: [],
    },
    shotDistribution: {
      promo: 0.16,
      philosophy: 0.35,
      personal: 0.28,
      assists: 0.13,
      setup: 0.08,
    },
    efficiency: {
      socialTS: 0.085,
      socialEFG: 0.098,
      assistRate: 0.13,
      reboundRate: 0.07,
      turnoverRate: 0.04,
    },
    takeoverLevel: 1,
    takeoverSurface: null,
  },
  {
    id: "emp_011",
    name: "Willie Williams",
    role: "Operations / Finance",
    archetype: "Human Halo",
    archetypeDescription: "Boosts teammates' performance by presence alone. The floor general.",
    department: "Operations",
    isGM: false,
    productLine: "Every (company)",
    surfaceIQ: 52,
    coverageScore: 32,
    trustGravity: 48,
    assistCredit: 55,
    shotSelection: 45,
    signatureMove: "The Quiet Assist — operational excellence that enables the team's public plays",
    badges: {
      gold: ["Operational Trust"],
      silver: ["LinkedIn"],
      bronze: [],
      hof: [],
    },
    shotDistribution: {
      promo: 0.1,
      philosophy: 0.2,
      personal: 0.45,
      assists: 0.2,
      setup: 0.05,
    },
    efficiency: {
      socialTS: 0.045,
      socialEFG: 0.052,
      assistRate: 0.2,
      reboundRate: 0.04,
      turnoverRate: 0.02,
    },
    takeoverLevel: 0,
    takeoverSurface: null,
  },
  {
    id: "emp_012",
    name: "Lucas Crespo",
    role: "Designer",
    archetype: "Surface Specialist",
    archetypeDescription: "Elite at one surface type, average elsewhere. The 3-level scorer.",
    department: "Design",
    isGM: false,
    productLine: "Every (design)",
    surfaceIQ: 61,
    coverageScore: 41,
    trustGravity: 58,
    assistCredit: 52,
    shotSelection: 65,
    signatureMove: "The Visual Essay — design thinking communicated through image and motion",
    badges: {
      gold: ["Design Authority", "External Interview"],
      silver: ["LinkedIn"],
      bronze: ["X"],
      hof: [],
    },
    shotDistribution: {
      promo: 0.12,
      philosophy: 0.3,
      personal: 0.38,
      assists: 0.12,
      setup: 0.08,
    },
    efficiency: {
      socialTS: 0.068,
      socialEFG: 0.078,
      assistRate: 0.12,
      reboundRate: 0.06,
      turnoverRate: 0.04,
    },
    takeoverLevel: 1,
    takeoverSurface: "external_interview",
  },
  {
    id: "emp_013",
    name: "Mike Taylor",
    role: "Engineer / Author",
    archetype: "Authority Anchor",
    archetypeDescription: "Dominates specific authority surfaces. The post powerhouse.",
    department: "Engineering",
    isGM: false,
    productLine: "Every (technical content)",
    surfaceIQ: 77,
    coverageScore: 58,
    trustGravity: 86,
    assistCredit: 64,
    shotSelection: 82,
    signatureMove: "The O'Reilly Authority — technical depth validated by publisher-grade credibility",
    badges: {
      gold: ["O'Reilly Author", "Technical Authority", "LinkedIn Enterprise"],
      silver: ["X Presence"],
      bronze: ["GitHub"],
      hof: ["Book Authority"],
    },
    shotDistribution: {
      promo: 0.15,
      philosophy: 0.45,
      personal: 0.2,
      assists: 0.12,
      setup: 0.08,
    },
    efficiency: {
      socialTS: 0.115,
      socialEFG: 0.132,
      assistRate: 0.12,
      reboundRate: 0.1,
      turnoverRate: 0.03,
    },
    takeoverLevel: 3,
    takeoverSurface: "book",
  },
  {
    id: "emp_014",
    name: "Alex Duffy",
    role: "Engineer",
    archetype: "Builder Philosopher",
    archetypeDescription: "Rare combo: technical depth + public communication range. The 2-way stretch five.",
    department: "Engineering",
    isGM: false,
    productLine: "Cora",
    surfaceIQ: 58,
    coverageScore: 38,
    trustGravity: 52,
    assistCredit: 48,
    shotSelection: 55,
    signatureMove: "The Technical Clarifier — complex engineering concepts made accessible",
    badges: {
      gold: ["GitHub Quality"],
      silver: ["X"],
      bronze: ["LinkedIn"],
      hof: [],
    },
    shotDistribution: {
      promo: 0.1,
      philosophy: 0.4,
      personal: 0.3,
      assists: 0.12,
      setup: 0.08,
    },
    efficiency: {
      socialTS: 0.058,
      socialEFG: 0.068,
      assistRate: 0.12,
      reboundRate: 0.06,
      turnoverRate: 0.03,
    },
    takeoverLevel: 1,
    takeoverSurface: "github",
  },
  {
    id: "emp_015",
    name: "Rhea Purohit",
    role: "Growth / Marketing",
    archetype: "Launch Sixth Man",
    archetypeDescription: "Comes off bench cold, heats up fast for specific launches. The microwave.",
    department: "Growth",
    isGM: false,
    productLine: "Every (growth)",
    surfaceIQ: 63,
    coverageScore: 42,
    trustGravity: 61,
    assistCredit: 58,
    shotSelection: 64,
    signatureMove: "The Launch Sprint — rapid execution on growth campaigns with surgical timing",
    badges: {
      gold: ["Personal Site", "Launch Execution"],
      silver: ["X", "LinkedIn"],
      bronze: [],
      hof: [],
    },
    shotDistribution: {
      promo: 0.2,
      philosophy: 0.25,
      personal: 0.3,
      assists: 0.15,
      setup: 0.1,
    },
    efficiency: {
      socialTS: 0.075,
      socialEFG: 0.088,
      assistRate: 0.15,
      reboundRate: 0.07,
      turnoverRate: 0.05,
    },
    takeoverLevel: 1,
    takeoverSurface: "personal_site",
  },
  {
    id: "emp_016",
    name: "Anthony Scarpulla",
    role: "Engineer",
    archetype: "Builder Philosopher",
    archetypeDescription: "Rare combo: technical depth + public communication range. The 2-way stretch five.",
    department: "Engineering",
    isGM: false,
    productLine: "Cora",
    surfaceIQ: 35,
    coverageScore: 18,
    trustGravity: 22,
    assistCredit: 30,
    shotSelection: 40,
    signatureMove: "The Quiet Build — technical excellence without the spotlight",
    badges: {
      gold: [],
      silver: [],
      bronze: [],
      hof: [],
    },
    shotDistribution: {
      promo: 0.05,
      philosophy: 0.25,
      personal: 0.4,
      assists: 0.2,
      setup: 0.1,
    },
    efficiency: {
      socialTS: 0.0,
      socialEFG: 0.0,
      assistRate: 0.2,
      reboundRate: 0.02,
      turnoverRate: 0.0,
    },
    takeoverLevel: 0,
    takeoverSurface: null,
  },
];
