// /lib/data/opportunities.ts
// Real researched seed data — Surface opportunities from the report

export type OpportunityImpact = "low" | "medium" | "high";
export type OpportunityEffort = "low" | "medium" | "high" | "na";
export type OpportunityConfidence = "direct" | "estimated" | "modeled" | "hypothesis";

export interface SurfaceOpportunity {
  id: string;
  entityType: "company" | "employee" | "product";
  entityId: string;
  entityName: string;
  title: string;
  description: string;
  surface: string;
  impact: OpportunityImpact;
  effort: OpportunityEffort;
  evidence: string[];
  recommendedAction: string;
  confidence: OpportunityConfidence;
}

export const opportunities: SurfaceOpportunity[] = [
  {
    id: "opp_001",
    entityType: "company",
    entityId: "comp_every_001",
    entityName: "Every",
    title: "Product Hunt Maker Gap",
    description: "5 Product Hunt product pages exist. 0 maker profiles are attached. This is a massive attribution leak.",
    surface: "product_hunt",
    impact: "high",
    effort: "low",
    evidence: ["5 PH pages verified", "0 maker profiles attached", "Dan, Austin, Brandon, Kieran are makers but not linked"],
    recommendedAction: "Attach Dan Shipper as primary maker on all 5 products. Attach product-specific makers (Brandon → Cora, Kieran → Cora tech).",
    confidence: "direct",
  },
  {
    id: "opp_002",
    entityType: "company",
    entityId: "comp_every_001",
    entityName: "Every",
    title: "GitHub Org Invisibility",
    description: "Every has a GitHub org but limited visibility. Only 1 employee (Kieran) has visible GitHub presence. Builder credibility gap.",
    surface: "github",
    impact: "high",
    effort: "medium",
    evidence: ["GitHub org exists but underutilized", "Only Kieran visible", "Builder audience expects GitHub presence"],
    recommendedAction: "Activate Every GitHub org. Pin repos. Add team section. Encourage engineers to make profiles visible.",
    confidence: "direct",
  },
  {
    id: "opp_003",
    entityType: "company",
    entityId: "comp_every_001",
    entityName: "Every",
    title: "YouTube Channel Absence",
    description: "No company YouTube channel. Video content is increasingly important for builder trust.",
    surface: "youtube",
    impact: "medium",
    effort: "high",
    evidence: ["No company channel", "Founder video essays are trending", "Dan's voice would translate well"],
    recommendedAction: "Create Every YouTube channel. Start with repurposed podcast clips and founder essays.",
    confidence: "estimated",
  },
  {
    id: "opp_004",
    entityType: "employee",
    entityId: "emp_001",
    entityName: "Dan Shipper",
    title: "Founder Video Essays",
    description: "Dan's writing voice would translate to video essays. High trust gravity potential.",
    surface: "youtube",
    impact: "high",
    effort: "high",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Dan's writing voice would translate to video essays. High trust gravity potential.",
    confidence: "estimated",
  },
  {
    id: "opp_005",
    entityType: "employee",
    entityId: "emp_001",
    entityName: "Dan Shipper",
    title: "Every Org Visibility",
    description: "Attach Every products to GitHub org. Builder credibility.",
    surface: "github",
    impact: "medium",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Attach Every products to GitHub org. Builder credibility.",
    confidence: "direct",
  },
  {
    id: "opp_006",
    entityType: "employee",
    entityId: "emp_002",
    entityName: "Austin Tedesco",
    title: "Operationalize Austin's Substack",
    description: "Substack discovered but underutilized. Cross-promote with Every newsletter for compounding.",
    surface: "substack",
    impact: "high",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Substack discovered but underutilized. Cross-promote with Every newsletter for compounding.",
    confidence: "direct",
  },
  {
    id: "opp_007",
    entityType: "employee",
    entityId: "emp_002",
    entityName: "Austin Tedesco",
    title: "Claim Product Hunt Maker Profile",
    description: "Attach Austin as maker on Every products. Attribution leak.",
    surface: "product_hunt",
    impact: "medium",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Attach Austin as maker on Every products. Attribution leak.",
    confidence: "direct",
  },
  {
    id: "opp_008",
    entityType: "employee",
    entityId: "emp_002",
    entityName: "Austin Tedesco",
    title: "Growth Engineering Visibility",
    description: "Show growth experiments as code. Builder credibility.",
    surface: "github",
    impact: "medium",
    effort: "medium",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Show growth experiments as code. Builder credibility.",
    confidence: "estimated",
  },
  {
    id: "opp_009",
    entityType: "employee",
    entityId: "emp_003",
    entityName: "Brandon Gell",
    title: "Cora Product Chronicle",
    description: "Weekly 'Building Cora' transparency posts. High authenticity fit.",
    surface: "substack",
    impact: "high",
    effort: "medium",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Weekly 'Building Cora' transparency posts. High authenticity fit.",
    confidence: "estimated",
  },
  {
    id: "opp_010",
    entityType: "employee",
    entityId: "emp_003",
    entityName: "Brandon Gell",
    title: "Attach Maker Profile to Cora",
    description: "Brandon is maker on PH but not linked to Cora. Fix attribution.",
    surface: "product_hunt",
    impact: "medium",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Brandon is maker on PH but not linked to Cora. Fix attribution.",
    confidence: "direct",
  },
  {
    id: "opp_011",
    entityType: "employee",
    entityId: "emp_004",
    entityName: "Kate Lee",
    title: "Editorial Portfolio Hub",
    description: "Aggregate best articles, editorial philosophy, writing process.",
    surface: "personal_site",
    impact: "medium",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Aggregate best articles, editorial philosophy, writing process.",
    confidence: "estimated",
  },
  {
    id: "opp_012",
    entityType: "employee",
    entityId: "emp_005",
    entityName: "Kieran Klaassen",
    title: "Attach Maker Profile to Cora",
    description: "Kieran is the face of Cora's engineering. Attach maker profile for attribution.",
    surface: "product_hunt",
    impact: "high",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Kieran is the face of Cora's engineering. Attach maker profile for attribution.",
    confidence: "direct",
  },
  {
    id: "opp_013",
    entityType: "employee",
    entityId: "emp_005",
    entityName: "Kieran Klaassen",
    title: "Builder's Chronicle",
    description: "Technical build logs. High conviction fit. Would attract engineering audience.",
    surface: "substack",
    impact: "medium",
    effort: "medium",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Technical build logs. High conviction fit. Would attract engineering audience.",
    confidence: "estimated",
  },
  {
    id: "opp_014",
    entityType: "employee",
    entityId: "emp_006",
    entityName: "Yash Poojary",
    title: "Growth Memes / Carousels",
    description: "Yash's personality would translate to visual growth content. Instagram/TikTok opportunity.",
    surface: "instagram",
    impact: "medium",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Yash's personality would translate to visual growth content. Instagram/TikTok opportunity.",
    confidence: "estimated",
  },
  {
    id: "opp_015",
    entityType: "employee",
    entityId: "emp_006",
    entityName: "Yash Poojary",
    title: "Growth Engineering Visibility",
    description: "Show growth experiments as code. Builder credibility.",
    surface: "github",
    impact: "medium",
    effort: "medium",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Show growth experiments as code. Builder credibility.",
    confidence: "estimated",
  },
  {
    id: "opp_016",
    entityType: "employee",
    entityId: "emp_007",
    entityName: "Naveen Naidu",
    title: "Engineering Visibility",
    description: "Show Cora build process. Cultural + technical credibility.",
    surface: "github",
    impact: "medium",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Show Cora build process. Cultural + technical credibility.",
    confidence: "estimated",
  },
  {
    id: "opp_017",
    entityType: "employee",
    entityId: "emp_008",
    entityName: "Natalia Quintero",
    title: "Enterprise Consulting Chronicle",
    description: "Weekly enterprise AI insights. Natalia is already generating leads in LinkedIn comments — a newsletter would compound this.",
    surface: "substack",
    impact: "high",
    effort: "medium",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Weekly enterprise AI insights. Natalia is already generating leads in LinkedIn comments — a newsletter would compound this.",
    confidence: "direct",
  },
  {
    id: "opp_018",
    entityType: "employee",
    entityId: "emp_008",
    entityName: "Natalia Quintero",
    title: "Consulting Portfolio",
    description: "Case studies, testimonials, service offerings. Direct lead generation.",
    surface: "personal_site",
    impact: "high",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Case studies, testimonials, service offerings. Direct lead generation.",
    confidence: "estimated",
  },
  {
    id: "opp_019",
    entityType: "employee",
    entityId: "emp_009",
    entityName: "Katie Parrott",
    title: "Writer Portfolio Hub",
    description: "Aggregate best work, writing philosophy, process.",
    surface: "personal_site",
    impact: "medium",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Aggregate best work, writing philosophy, process.",
    confidence: "estimated",
  },
  {
    id: "opp_020",
    entityType: "employee",
    entityId: "emp_010",
    entityName: "Laura Entis",
    title: "Laura Needs Twitter",
    description: "A writer without Twitter is a shooter without a court. This is the highest-priority absent surface on the roster.",
    surface: "x",
    impact: "high",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "A writer without Twitter is a shooter without a court. This is the highest-priority absent surface on the roster.",
    confidence: "direct",
  },
  {
    id: "opp_021",
    entityType: "employee",
    entityId: "emp_010",
    entityName: "Laura Entis",
    title: "Reporter's Notebook",
    description: "Behind-the-scenes reporting process. Would differentiate her from other Every writers.",
    surface: "substack",
    impact: "medium",
    effort: "medium",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Behind-the-scenes reporting process. Would differentiate her from other Every writers.",
    confidence: "estimated",
  },
  {
    id: "opp_022",
    entityType: "employee",
    entityId: "emp_011",
    entityName: "Willie Williams",
    title: "Operations Transparency",
    description: "Startup ops/finance transparency is rare and valuable. Would differentiate Every.",
    surface: "x",
    impact: "medium",
    effort: "medium",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Startup ops/finance transparency is rare and valuable. Would differentiate Every.",
    confidence: "estimated",
  },
  {
    id: "opp_023",
    entityType: "employee",
    entityId: "emp_012",
    entityName: "Lucas Crespo",
    title: "Design Portfolio on Instagram",
    description: "Visual-first surface for a designer. Natural fit. Would showcase Every's design quality.",
    surface: "instagram",
    impact: "medium",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Visual-first surface for a designer. Natural fit. Would showcase Every's design quality.",
    confidence: "direct",
  },
  {
    id: "opp_024",
    entityType: "employee",
    entityId: "emp_012",
    entityName: "Lucas Crespo",
    title: "Dribbble Portfolio",
    description: "Design community authority. Would attract design-minded customers.",
    surface: "dribbble",
    impact: "medium",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Design community authority. Would attract design-minded customers.",
    confidence: "estimated",
  },
  {
    id: "opp_025",
    entityType: "employee",
    entityId: "emp_012",
    entityName: "Lucas Crespo",
    title: "Design Portfolio Site",
    description: "Centralize external interview + design work. Authority anchor.",
    surface: "personal_site",
    impact: "medium",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Centralize external interview + design work. Authority anchor.",
    confidence: "estimated",
  },
  {
    id: "opp_026",
    entityType: "employee",
    entityId: "emp_013",
    entityName: "Mike Taylor",
    title: "Author + Consultant Hub",
    description: "Combine O'Reilly authority with consulting offerings. Direct lead generation.",
    surface: "personal_site",
    impact: "high",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Combine O'Reilly authority with consulting offerings. Direct lead generation.",
    confidence: "direct",
  },
  {
    id: "opp_027",
    entityType: "employee",
    entityId: "emp_013",
    entityName: "Mike Taylor",
    title: "Technical Deep Dives Newsletter",
    description: "O'Reilly-level content in newsletter format. Would attract enterprise audience.",
    surface: "substack",
    impact: "high",
    effort: "medium",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "O'Reilly-level content in newsletter format. Would attract enterprise audience.",
    confidence: "estimated",
  },
  {
    id: "opp_028",
    entityType: "employee",
    entityId: "emp_013",
    entityName: "Mike Taylor",
    title: "Attach Maker Profile to Every Products",
    description: "Mike's technical authority + Product Hunt = builder trust.",
    surface: "product_hunt",
    impact: "medium",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Mike's technical authority + Product Hunt = builder trust.",
    confidence: "direct",
  },
  {
    id: "opp_029",
    entityType: "employee",
    entityId: "emp_014",
    entityName: "Alex Duffy",
    title: "Engineering Chronicle",
    description: "Technical build logs. Would complement Kieran's conviction with practical depth.",
    surface: "substack",
    impact: "medium",
    effort: "medium",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Technical build logs. Would complement Kieran's conviction with practical depth.",
    confidence: "estimated",
  },
  {
    id: "opp_030",
    entityType: "employee",
    entityId: "emp_015",
    entityName: "Rhea Purohit",
    title: "Claim Maker Profile",
    description: "Rhea's launch execution + Product Hunt = attribution for Every launches.",
    surface: "product_hunt",
    impact: "medium",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Rhea's launch execution + Product Hunt = attribution for Every launches.",
    confidence: "direct",
  },
  {
    id: "opp_031",
    entityType: "employee",
    entityId: "emp_015",
    entityName: "Rhea Purohit",
    title: "Growth Playbook Newsletter",
    description: "Document launch experiments. Would attract growth-minded audience.",
    surface: "substack",
    impact: "medium",
    effort: "medium",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Document launch experiments. Would attract growth-minded audience.",
    confidence: "estimated",
  },
  {
    id: "opp_032",
    entityType: "employee",
    entityId: "emp_016",
    entityName: "Anthony Scarpulla",
    title: "Engineering Visibility",
    description: "Anthony's technical work is invisible. GitHub would make it visible.",
    surface: "github",
    impact: "medium",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Anthony's technical work is invisible. GitHub would make it visible.",
    confidence: "direct",
  },
  {
    id: "opp_033",
    entityType: "employee",
    entityId: "emp_016",
    entityName: "Anthony Scarpulla",
    title: "Professional Presence",
    description: "Basic LinkedIn profile. Would enable recruiting and partnership visibility.",
    surface: "linkedin",
    impact: "low",
    effort: "low",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Basic LinkedIn profile. Would enable recruiting and partnership visibility.",
    confidence: "direct",
  },
  {
    id: "opp_034",
    entityType: "employee",
    entityId: "emp_016",
    entityName: "Anthony Scarpulla",
    title: "Technical Voice",
    description: "Would Anthony want a public voice? Assess before recommending.",
    surface: "x",
    impact: "medium",
    effort: "medium",
    evidence: ["Surface Intelligence Report finding"],
    recommendedAction: "Would Anthony want a public voice? Assess before recommending.",
    confidence: "hypothesis",
  },
];
