// /lib/data/scoutingNotes.ts
// Real researched seed data — Scouting notes for each employee

export interface ScoutingNote {
  id: string;
  employeeId: string;
  employeeName: string;
  note: string;
  type: "strength" | "opportunity" | "insight" | "caution";
}

export const scoutingNotes: ScoutingNote[] = [
  {
    id: "note_001",
    employeeId: "emp_001",
    employeeName: "Dan Shipper",
    note: "Elite at long-form narrative. His essays are the team's most reliable trust-building asset.",
    type: "strength",
  },
  {
    id: "note_002",
    employeeId: "emp_001",
    employeeName: "Dan Shipper",
    note: "Low promo density (12%) but high conversion when he does ask. The anti-spammer.",
    type: "insight",
  },
  {
    id: "note_003",
    employeeId: "emp_001",
    employeeName: "Dan Shipper",
    note: "Absent on video surfaces — biggest untapped potential for audience expansion.",
    type: "opportunity",
  },
  {
    id: "note_004",
    employeeId: "emp_002",
    employeeName: "Austin Tedesco",
    note: "Elite assist rate (17.8%). The team's best playmaker — creates scoring chances for others.",
    type: "strength",
  },
  {
    id: "note_005",
    employeeId: "emp_002",
    employeeName: "Austin Tedesco",
    note: "Low promo density (9%) but highest TS% relative to follower count. Efficient volume.",
    type: "strength",
  },
  {
    id: "note_006",
    employeeId: "emp_002",
    employeeName: "Austin Tedesco",
    note: "Substack is the highest-opportunity absent surface — content exists in his head, the surface doesn't.",
    type: "strength",
  },
  {
    id: "note_007",
    employeeId: "emp_003",
    employeeName: "Brandon Gell",
    note: "Highest authenticity FT% on the roster. Unpolished posts outperform polished ones.",
    type: "strength",
  },
  {
    id: "note_008",
    employeeId: "emp_003",
    employeeName: "Brandon Gell",
    note: "Low coverage score (52) but high trust gravity per post. Quality over quantity.",
    type: "insight",
  },
  {
    id: "note_009",
    employeeId: "emp_003",
    employeeName: "Brandon Gell",
    note: "Personal shot distribution (45%) is highest on team — his voice IS the brand.",
    type: "strength",
  },
  {
    id: "note_010",
    employeeId: "emp_004",
    employeeName: "Kate Lee",
    note: "Highest philosophy shot distribution (42%). The team's intellectual anchor.",
    type: "strength",
  },
  {
    id: "note_011",
    employeeId: "emp_004",
    employeeName: "Kate Lee",
    note: "Low turnover rate (3%). Consistent, reliable editorial presence.",
    type: "insight",
  },
  {
    id: "note_012",
    employeeId: "emp_004",
    employeeName: "Kate Lee",
    note: "Teaches the GMs about editorial trust — her process is the playbook.",
    type: "insight",
  },
  {
    id: "note_013",
    employeeId: "emp_005",
    employeeName: "Kieran Klaassen",
    note: "Highest philosophy shot distribution (55%). The team's conviction anchor.",
    type: "strength",
  },
  {
    id: "note_014",
    employeeId: "emp_005",
    employeeName: "Kieran Klaassen",
    note: "60x gap: philosophy tweet gets 315 likes, promo tweet gets 5. Model says: 2 mid-range passes → 1 three-pointer.",
    type: "opportunity",
  },
  {
    id: "note_015",
    employeeId: "emp_005",
    employeeName: "Kieran Klaassen",
    note: "Only visible GitHub employee. This is a massive differentiator for builder trust.",
    type: "insight",
  },
  {
    id: "note_016",
    employeeId: "emp_005",
    employeeName: "Kieran Klaassen",
    note: "Lowest turnover rate (2%). Every post is intentional.",
    type: "insight",
  },
  {
    id: "note_017",
    employeeId: "emp_006",
    employeeName: "Yash Poojary",
    note: "Teaches Dan that promo can have personality. His voice bridges growth and authenticity.",
    type: "insight",
  },
  {
    id: "note_018",
    employeeId: "emp_006",
    employeeName: "Yash Poojary",
    note: "Highest promo density (22%) on the growth team — but makes it feel natural.",
    type: "strength",
  },
  {
    id: "note_019",
    employeeId: "emp_006",
    employeeName: "Yash Poojary",
    note: "Instagram is a natural fit for his visual personality. Low-effort, medium-impact opportunity.",
    type: "opportunity",
  },
  {
    id: "note_020",
    employeeId: "emp_007",
    employeeName: "Naveen Naidu",
    note: "Highest personal shot distribution (55%). His humanity IS the marketing.",
    type: "strength",
  },
  {
    id: "note_021",
    employeeId: "emp_007",
    employeeName: "Naveen Naidu",
    note: "'Dia and Granola' tweet: 82 likes, zero ask. Free throws make 3s easier — his cultural posts build the floor for product launches.",
    type: "insight",
  },
  {
    id: "note_022",
    employeeId: "emp_007",
    employeeName: "Naveen Naidu",
    note: "Low promo density (5%) but high trust compounding. The team's best trust builder.",
    type: "strength",
  },
  {
    id: "note_023",
    employeeId: "emp_008",
    employeeName: "Natalia Quintero",
    note: "Already generating enterprise consulting leads in LinkedIn comments. The growth is happening — Surface IQ just makes it visible.",
    type: "insight",
  },
  {
    id: "note_024",
    employeeId: "emp_008",
    employeeName: "Natalia Quintero",
    note: "Highest shot selection score (83) on the sales team. Knows exactly when to ask.",
    type: "strength",
  },
  {
    id: "note_025",
    employeeId: "emp_008",
    employeeName: "Natalia Quintero",
    note: "LinkedIn is her court. Every other surface is an open lane.",
    type: "opportunity",
  },
  {
    id: "note_026",
    employeeId: "emp_009",
    employeeName: "Katie Parrott",
    note: "Strong editorial clarity. Complex topics become accessible in her hands.",
    type: "strength",
  },
  {
    id: "note_027",
    employeeId: "emp_009",
    employeeName: "Katie Parrott",
    note: "Balanced shot distribution. Not afraid to promo (14%) but keeps it editorial.",
    type: "insight",
  },
  {
    id: "note_028",
    employeeId: "emp_009",
    employeeName: "Katie Parrott",
    note: "Personal site is low-hanging fruit — would centralize her scattered authority.",
    type: "insight",
  },
  {
    id: "note_029",
    employeeId: "emp_010",
    employeeName: "Laura Entis",
    note: "No Twitter presence. For a writer, this is like a shooter without a court. Highest-priority fix.",
    type: "strength",
  },
  {
    id: "note_030",
    employeeId: "emp_010",
    employeeName: "Laura Entis",
    note: "Launch Sixth Man archetype: heats up fast during product moments, then cools. Needs a surface to heat on.",
    type: "opportunity",
  },
  {
    id: "note_031",
    employeeId: "emp_010",
    employeeName: "Laura Entis",
    note: "LinkedIn is her only verified surface. Everything else is an open lane.",
    type: "opportunity",
  },
  {
    id: "note_032",
    employeeId: "emp_011",
    employeeName: "Willie Williams",
    note: "Low coverage score (32) but high assist rate (20%). His operational work enables everyone else's public plays.",
    type: "insight",
  },
  {
    id: "note_033",
    employeeId: "emp_011",
    employeeName: "Willie Williams",
    note: "Not a public-facing player by design. His value is in the assist, not the shot.",
    type: "insight",
  },
  {
    id: "note_034",
    employeeId: "emp_011",
    employeeName: "Willie Williams",
    note: "X/Twitter would be a differentiation play — startup ops transparency is rare.",
    type: "insight",
  },
  {
    id: "note_035",
    employeeId: "emp_012",
    employeeName: "Lucas Crespo",
    note: "External interview is a verified authority surface. Use it as the anchor for other surfaces.",
    type: "insight",
  },
  {
    id: "note_036",
    employeeId: "emp_012",
    employeeName: "Lucas Crespo",
    note: "Instagram/Dribbble are natural fits for a designer. Low-effort, medium-impact.",
    type: "insight",
  },
  {
    id: "note_037",
    employeeId: "emp_012",
    employeeName: "Lucas Crespo",
    note: "His visual essay style would work on any image-first platform.",
    type: "insight",
  },
  {
    id: "note_038",
    employeeId: "emp_013",
    employeeName: "Mike Taylor",
    note: "O'Reilly book is the team's highest-confidence authority surface (98%). Use it everywhere.",
    type: "strength",
  },
  {
    id: "note_039",
    employeeId: "emp_013",
    employeeName: "Mike Taylor",
    note: "Highest trust gravity (86) among non-founders. His name carries weight.",
    type: "strength",
  },
  {
    id: "note_040",
    employeeId: "emp_013",
    employeeName: "Mike Taylor",
    note: "Personal site is the biggest open lane — combine book authority with consulting for direct revenue.",
    type: "opportunity",
  },
  {
    id: "note_041",
    employeeId: "emp_014",
    employeeName: "Alex Duffy",
    note: "Solid GitHub presence. One of the few engineers with visible code.",
    type: "insight",
  },
  {
    id: "note_042",
    employeeId: "emp_014",
    employeeName: "Alex Duffy",
    note: "Low volume but high philosophy density (40%). Quality over quantity.",
    type: "insight",
  },
  {
    id: "note_043",
    employeeId: "emp_014",
    employeeName: "Alex Duffy",
    note: "Substack would be a natural extension — practical engineering + build logs.",
    type: "insight",
  },
  {
    id: "note_044",
    employeeId: "emp_015",
    employeeName: "Rhea Purohit",
    note: "Personal site is a verified authority surface. Use it as the anchor.",
    type: "insight",
  },
  {
    id: "note_045",
    employeeId: "emp_015",
    employeeName: "Rhea Purohit",
    note: "Launch Sixth Man archetype: best when there's a specific campaign to execute.",
    type: "strength",
  },
  {
    id: "note_046",
    employeeId: "emp_015",
    employeeName: "Rhea Purohit",
    note: "Product Hunt maker profile is low-hanging fruit for launch attribution.",
    type: "insight",
  },
  {
    id: "note_047",
    employeeId: "emp_016",
    employeeName: "Anthony Scarpulla",
    note: "Invisible on all surfaces. Not a failure — a choice. But the team loses attribution for his work.",
    type: "insight",
  },
  {
    id: "note_048",
    employeeId: "emp_016",
    employeeName: "Anthony Scarpulla",
    note: "Lowest coverage score (18) and surface IQ (35) on the roster.",
    type: "insight",
  },
  {
    id: "note_049",
    employeeId: "emp_016",
    employeeName: "Anthony Scarpulla",
    note: "Decision needed: should Anthony have visible social presence? If yes, GitHub is the lowest-effort start.",
    type: "caution",
  },
  {
    id: "note_050",
    employeeId: "emp_016",
    employeeName: "Anthony Scarpulla",
    note: "If no, document the decision. Invisibility is valid if intentional.",
    type: "caution",
  },
];
