// /lib/data/surfaces.ts
// Real researched seed data — Surface presence for company + 16 employees

export type SurfaceType =
  | "website"
  | "x"
  | "linkedin"
  | "youtube"
  | "substack"
  | "newsletter"
  | "tiktok"
  | "github"
  | "instagram"
  | "podcast"
  | "product_hunt"
  | "app_store"
  | "personal_site"
  | "external_interview"
  | "book"
  | "referral_program"
  | "consulting"
  | "medium"
  | "devto"
  | "discord"
  | "figma"
  | "dribbble"
  | "twitch"
  | "calendly"
  | "other";

export type SurfaceStatus = "verified" | "likely" | "absent";

export interface SurfacePresence {
  id: string;
  entityType: "company" | "employee" | "product";
  entityId: string;
  entityName: string;
  surface: SurfaceType;
  label: string;
  handle?: string;
  url?: string;
  status: SurfaceStatus;
  discoveryMethod?: string;
  notes?: string;
  confidenceScore?: number;
}

export const surfacePresences: SurfacePresence[] = [
  {
    id: "surf_001",
    entityType: "company",
    entityId: "comp_every_001",
    entityName: "Every",
    surface: "x",
    label: "X / Twitter",
    handle: "@every",
    url: undefined,
    status: "verified",
    notes: "Primary company social surface",
    confidenceScore: 0.98,
  },
  {
    id: "surf_002",
    entityType: "company",
    entityId: "comp_every_001",
    entityName: "Every",
    surface: "linkedin",
    label: "LinkedIn",
    handle: "every-company",
    url: undefined,
    status: "verified",
    notes: "Company page",
    confidenceScore: 0.95,
  },
  {
    id: "surf_003",
    entityType: "company",
    entityId: "comp_every_001",
    entityName: "Every",
    surface: "youtube",
    label: "YouTube",
    handle: null,
    url: undefined,
    status: "absent",
    notes: "No company channel",
    confidenceScore: 0.1,
  },
  {
    id: "surf_004",
    entityType: "company",
    entityId: "comp_every_001",
    entityName: "Every",
    surface: "substack",
    label: "Substack",
    handle: "every",
    url: undefined,
    status: "verified",
    notes: "Every newsletter",
    confidenceScore: 0.97,
  },
  {
    id: "surf_005",
    entityType: "company",
    entityId: "comp_every_001",
    entityName: "Every",
    surface: "newsletter",
    label: "Newsletter",
    handle: null,
    url: undefined,
    status: "verified",
    notes: "Same as Substack",
    confidenceScore: 0.97,
  },
  {
    id: "surf_006",
    entityType: "company",
    entityId: "comp_every_001",
    entityName: "Every",
    surface: "github",
    label: "GitHub",
    handle: "everyhq",
    url: undefined,
    status: "likely",
    notes: "Org exists but limited visibility",
    confidenceScore: 0.65,
  },
  {
    id: "surf_007",
    entityType: "company",
    entityId: "comp_every_001",
    entityName: "Every",
    surface: "product_hunt",
    label: "Product Hunt",
    handle: "every",
    url: undefined,
    status: "verified",
    notes: "5 product pages, 0 maker profiles attached",
    confidenceScore: 0.9,
  },
  {
    id: "surf_008",
    entityType: "company",
    entityId: "comp_every_001",
    entityName: "Every",
    surface: "instagram",
    label: "Instagram",
    handle: null,
    url: undefined,
    status: "absent",
    notes: "No presence",
    confidenceScore: 0.05,
  },
  {
    id: "surf_009",
    entityType: "company",
    entityId: "comp_every_001",
    entityName: "Every",
    surface: "tiktok",
    label: "TikTok",
    handle: null,
    url: undefined,
    status: "absent",
    notes: "No presence",
    confidenceScore: 0.05,
  },
  {
    id: "surf_010",
    entityType: "company",
    entityId: "comp_every_001",
    entityName: "Every",
    surface: "personal_site",
    label: "Personal Site",
    handle: "every.to",
    url: undefined,
    status: "verified",
    notes: "Primary domain",
    confidenceScore: 0.99,
  },
  {
    id: "surf_011",
    entityType: "company",
    entityId: "comp_every_001",
    entityName: "Every",
    surface: "podcast",
    label: "Podcast",
    handle: null,
    url: undefined,
    status: "verified",
    notes: "Every podcast",
    confidenceScore: 0.85,
  },
  {
    id: "surf_012",
    entityType: "employee",
    entityId: "emp_001",
    entityName: "Dan Shipper",
    surface: "x",
    label: "X",
    handle: "@danshipper",
    url: "https://x.com/danshipper",
    status: "verified",
    notes: "Primary surface. Founder narrative + product updates.",
    confidenceScore: 0.98,
  },
  {
    id: "surf_013",
    entityType: "employee",
    entityId: "emp_001",
    entityName: "Dan Shipper",
    surface: "linkedin",
    label: "Linkedin",
    handle: "dan-shipper",
    url: "https://linkedin.com/in/dan-shipper",
    status: "verified",
    notes: "Professional presence, less active than X.",
    confidenceScore: 0.95,
  },
  {
    id: "surf_014",
    entityType: "employee",
    entityId: "emp_001",
    entityName: "Dan Shipper",
    surface: "substack",
    label: "Substack",
    handle: "danshipper",
    url: "https://danshipper.substack.com",
    status: "verified",
    notes: "Major authority surface. Long-form essays.",
    confidenceScore: 0.99,
  },
  {
    id: "surf_015",
    entityType: "employee",
    entityId: "emp_001",
    entityName: "Dan Shipper",
    surface: "newsletter",
    label: "Newsletter",
    handle: "n/a",
    url: "https://danshipper.substack.com",
    status: "verified",
    notes: "Same as Substack. High open rates.",
    confidenceScore: 0.99,
  },
  {
    id: "surf_016",
    entityType: "employee",
    entityId: "emp_001",
    entityName: "Dan Shipper",
    surface: "podcast",
    label: "Podcast",
    handle: "n/a",
    url: "https://every.to/podcast",
    status: "verified",
    notes: "Guest appearances and host of Every podcast.",
    confidenceScore: 0.85,
  },
  {
    id: "surf_017",
    entityType: "employee",
    entityId: "emp_001",
    entityName: "Dan Shipper",
    surface: "github",
    label: "Github",
    handle: "danshipper",
    url: "https://github.com/danshipper",
    status: "likely",
    notes: "Personal account visible. Limited code activity.",
    confidenceScore: 0.72,
  },
  {
    id: "surf_018",
    entityType: "employee",
    entityId: "emp_001",
    entityName: "Dan Shipper",
    surface: "youtube",
    label: "Youtube",
    handle: null,
    url: null,
    status: "absent",
    notes: "No dedicated channel. Occasional guest clips.",
    confidenceScore: 0.15,
  },
  {
    id: "surf_019",
    entityType: "employee",
    entityId: "emp_001",
    entityName: "Dan Shipper",
    surface: "instagram",
    label: "Instagram",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_020",
    entityType: "employee",
    entityId: "emp_001",
    entityName: "Dan Shipper",
    surface: "tiktok",
    label: "Tiktok",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_021",
    entityType: "employee",
    entityId: "emp_001",
    entityName: "Dan Shipper",
    surface: "product_hunt",
    label: "Product Hunt",
    handle: "danshipper",
    url: "https://producthunt.com/@danshipper",
    status: "verified",
    notes: "Maker on multiple products. No profile attached to Every products.",
    confidenceScore: 0.88,
  },
  {
    id: "surf_022",
    entityType: "employee",
    entityId: "emp_001",
    entityName: "Dan Shipper",
    surface: "personal_site",
    label: "Personal Site",
    handle: "danshipper.com",
    url: "https://danshipper.com",
    status: "verified",
    notes: "Authority anchor. Portfolio + essays.",
    confidenceScore: 0.95,
  },
  {
    id: "surf_023",
    entityType: "employee",
    entityId: "emp_002",
    entityName: "Austin Tedesco",
    surface: "x",
    label: "X",
    handle: "@austin_tedesco",
    url: "https://x.com/austin_tedesco",
    status: "verified",
    notes: "Primary surface. High-efficiency posts, strong engagement.",
    confidenceScore: 0.97,
  },
  {
    id: "surf_024",
    entityType: "employee",
    entityId: "emp_002",
    entityName: "Austin Tedesco",
    surface: "linkedin",
    label: "Linkedin",
    handle: "austin-tedesco",
    url: "https://linkedin.com/in/austin-tedesco",
    status: "verified",
    notes: "Professional growth content. Lower volume than X.",
    confidenceScore: 0.92,
  },
  {
    id: "surf_025",
    entityType: "employee",
    entityId: "emp_002",
    entityName: "Austin Tedesco",
    surface: "substack",
    label: "Substack",
    handle: "austintedesco",
    url: "https://austintedesco.substack.com",
    status: "verified",
    notes: "Discovered surface. Growth experiments + case studies.",
    confidenceScore: 0.88,
  },
  {
    id: "surf_026",
    entityType: "employee",
    entityId: "emp_002",
    entityName: "Austin Tedesco",
    surface: "newsletter",
    label: "Newsletter",
    handle: "n/a",
    url: "https://austintedesco.substack.com",
    status: "verified",
    notes: "Same as Substack. High signal-to-noise.",
    confidenceScore: 0.88,
  },
  {
    id: "surf_027",
    entityType: "employee",
    entityId: "emp_002",
    entityName: "Austin Tedesco",
    surface: "github",
    label: "Github",
    handle: null,
    url: null,
    status: "absent",
    notes: "No visible presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_028",
    entityType: "employee",
    entityId: "emp_002",
    entityName: "Austin Tedesco",
    surface: "youtube",
    label: "Youtube",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_029",
    entityType: "employee",
    entityId: "emp_002",
    entityName: "Austin Tedesco",
    surface: "instagram",
    label: "Instagram",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_030",
    entityType: "employee",
    entityId: "emp_002",
    entityName: "Austin Tedesco",
    surface: "tiktok",
    label: "Tiktok",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_031",
    entityType: "employee",
    entityId: "emp_002",
    entityName: "Austin Tedesco",
    surface: "product_hunt",
    label: "Product Hunt",
    handle: null,
    url: null,
    status: "absent",
    notes: "No maker profile attached to Every products.",
    confidenceScore: 0.15,
  },
  {
    id: "surf_032",
    entityType: "employee",
    entityId: "emp_002",
    entityName: "Austin Tedesco",
    surface: "personal_site",
    label: "Personal Site",
    handle: null,
    url: null,
    status: "absent",
    notes: "No dedicated site.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_033",
    entityType: "employee",
    entityId: "emp_003",
    entityName: "Brandon Gell",
    surface: "x",
    label: "X",
    handle: "@brandongell",
    url: "https://x.com/brandongell",
    status: "verified",
    notes: "Active. Product updates + authentic takes.",
    confidenceScore: 0.88,
  },
  {
    id: "surf_034",
    entityType: "employee",
    entityId: "emp_003",
    entityName: "Brandon Gell",
    surface: "linkedin",
    label: "Linkedin",
    handle: "brandon-gell",
    url: "https://linkedin.com/in/brandon-gell",
    status: "verified",
    notes: "Professional presence.",
    confidenceScore: 0.82,
  },
  {
    id: "surf_035",
    entityType: "employee",
    entityId: "emp_003",
    entityName: "Brandon Gell",
    surface: "substack",
    label: "Substack",
    handle: null,
    url: null,
    status: "absent",
    notes: "No dedicated newsletter.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_036",
    entityType: "employee",
    entityId: "emp_003",
    entityName: "Brandon Gell",
    surface: "github",
    label: "Github",
    handle: null,
    url: null,
    status: "absent",
    notes: "No visible presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_037",
    entityType: "employee",
    entityId: "emp_003",
    entityName: "Brandon Gell",
    surface: "youtube",
    label: "Youtube",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_038",
    entityType: "employee",
    entityId: "emp_003",
    entityName: "Brandon Gell",
    surface: "instagram",
    label: "Instagram",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_039",
    entityType: "employee",
    entityId: "emp_003",
    entityName: "Brandon Gell",
    surface: "tiktok",
    label: "Tiktok",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_040",
    entityType: "employee",
    entityId: "emp_003",
    entityName: "Brandon Gell",
    surface: "product_hunt",
    label: "Product Hunt",
    handle: "brandongell",
    url: "https://producthunt.com/@brandongell",
    status: "verified",
    notes: "Maker profile exists. Not attached to Cora.",
    confidenceScore: 0.8,
  },
  {
    id: "surf_041",
    entityType: "employee",
    entityId: "emp_003",
    entityName: "Brandon Gell",
    surface: "personal_site",
    label: "Personal Site",
    handle: null,
    url: null,
    status: "absent",
    notes: "No dedicated site.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_042",
    entityType: "employee",
    entityId: "emp_004",
    entityName: "Kate Lee",
    surface: "x",
    label: "X",
    handle: "@katelee",
    url: "https://x.com/katelee",
    status: "verified",
    notes: "Editorial takes, article promotion.",
    confidenceScore: 0.85,
  },
  {
    id: "surf_043",
    entityType: "employee",
    entityId: "emp_004",
    entityName: "Kate Lee",
    surface: "linkedin",
    label: "Linkedin",
    handle: "kate-lee",
    url: "https://linkedin.com/in/kate-lee",
    status: "verified",
    notes: "Professional editorial presence.",
    confidenceScore: 0.8,
  },
  {
    id: "surf_044",
    entityType: "employee",
    entityId: "emp_004",
    entityName: "Kate Lee",
    surface: "substack",
    label: "Substack",
    handle: "katelee",
    url: "https://katelee.substack.com",
    status: "verified",
    notes: "Personal editorial newsletter.",
    confidenceScore: 0.82,
  },
  {
    id: "surf_045",
    entityType: "employee",
    entityId: "emp_004",
    entityName: "Kate Lee",
    surface: "github",
    label: "Github",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_046",
    entityType: "employee",
    entityId: "emp_004",
    entityName: "Kate Lee",
    surface: "youtube",
    label: "Youtube",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_047",
    entityType: "employee",
    entityId: "emp_004",
    entityName: "Kate Lee",
    surface: "instagram",
    label: "Instagram",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_048",
    entityType: "employee",
    entityId: "emp_004",
    entityName: "Kate Lee",
    surface: "tiktok",
    label: "Tiktok",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_049",
    entityType: "employee",
    entityId: "emp_004",
    entityName: "Kate Lee",
    surface: "product_hunt",
    label: "Product Hunt",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_050",
    entityType: "employee",
    entityId: "emp_004",
    entityName: "Kate Lee",
    surface: "personal_site",
    label: "Personal Site",
    handle: null,
    url: null,
    status: "absent",
    notes: "No dedicated site.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_051",
    entityType: "employee",
    entityId: "emp_005",
    entityName: "Kieran Klaassen",
    surface: "x",
    label: "X",
    handle: "@kieranklaassen",
    url: "https://x.com/kieranklaassen",
    status: "verified",
    notes: "Conviction tweets. Technical + product philosophy.",
    confidenceScore: 0.92,
  },
  {
    id: "surf_052",
    entityType: "employee",
    entityId: "emp_005",
    entityName: "Kieran Klaassen",
    surface: "linkedin",
    label: "Linkedin",
    handle: "kieran-klaassen",
    url: "https://linkedin.com/in/kieran-klaassen",
    status: "verified",
    notes: "Professional builder presence.",
    confidenceScore: 0.85,
  },
  {
    id: "surf_053",
    entityType: "employee",
    entityId: "emp_005",
    entityName: "Kieran Klaassen",
    surface: "github",
    label: "Github",
    handle: "kieranklaassen",
    url: "https://github.com/kieranklaassen",
    status: "verified",
    notes: "Only visible GitHub employee. Key differentiator.",
    confidenceScore: 0.95,
  },
  {
    id: "surf_054",
    entityType: "employee",
    entityId: "emp_005",
    entityName: "Kieran Klaassen",
    surface: "substack",
    label: "Substack",
    handle: null,
    url: null,
    status: "absent",
    notes: "No dedicated newsletter.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_055",
    entityType: "employee",
    entityId: "emp_005",
    entityName: "Kieran Klaassen",
    surface: "youtube",
    label: "Youtube",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_056",
    entityType: "employee",
    entityId: "emp_005",
    entityName: "Kieran Klaassen",
    surface: "instagram",
    label: "Instagram",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_057",
    entityType: "employee",
    entityId: "emp_005",
    entityName: "Kieran Klaassen",
    surface: "tiktok",
    label: "Tiktok",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_058",
    entityType: "employee",
    entityId: "emp_005",
    entityName: "Kieran Klaassen",
    surface: "product_hunt",
    label: "Product Hunt",
    handle: "kieranklaassen",
    url: "https://producthunt.com/@kieranklaassen",
    status: "verified",
    notes: "Maker profile exists. Not attached to Cora.",
    confidenceScore: 0.78,
  },
  {
    id: "surf_059",
    entityType: "employee",
    entityId: "emp_005",
    entityName: "Kieran Klaassen",
    surface: "personal_site",
    label: "Personal Site",
    handle: "kieranklaassen.com",
    url: "https://kieranklaassen.com",
    status: "verified",
    notes: "Personal product site. Builder credibility.",
    confidenceScore: 0.88,
  },
  {
    id: "surf_060",
    entityType: "employee",
    entityId: "emp_005",
    entityName: "Kieran Klaassen",
    surface: "podcast",
    label: "Podcast",
    handle: "n/a",
    url: "https://kieranklaassen.com/podcast",
    status: "verified",
    notes: "Personal podcast. Technical deep dives.",
    confidenceScore: 0.8,
  },
  {
    id: "surf_061",
    entityType: "employee",
    entityId: "emp_006",
    entityName: "Yash Poojary",
    surface: "x",
    label: "X",
    handle: "@yashpoojary",
    url: "https://x.com/yashpoojary",
    status: "verified",
    notes: "Personality-driven growth content. Promo can have personality.",
    confidenceScore: 0.88,
  },
  {
    id: "surf_062",
    entityType: "employee",
    entityId: "emp_006",
    entityName: "Yash Poojary",
    surface: "linkedin",
    label: "Linkedin",
    handle: "yash-poojary",
    url: "https://linkedin.com/in/yash-poojary",
    status: "verified",
    notes: "Professional presence.",
    confidenceScore: 0.78,
  },
  {
    id: "surf_063",
    entityType: "employee",
    entityId: "emp_006",
    entityName: "Yash Poojary",
    surface: "github",
    label: "Github",
    handle: null,
    url: null,
    status: "absent",
    notes: "No visible presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_064",
    entityType: "employee",
    entityId: "emp_006",
    entityName: "Yash Poojary",
    surface: "substack",
    label: "Substack",
    handle: null,
    url: null,
    status: "absent",
    notes: "No dedicated newsletter.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_065",
    entityType: "employee",
    entityId: "emp_006",
    entityName: "Yash Poojary",
    surface: "youtube",
    label: "Youtube",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_066",
    entityType: "employee",
    entityId: "emp_006",
    entityName: "Yash Poojary",
    surface: "instagram",
    label: "Instagram",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_067",
    entityType: "employee",
    entityId: "emp_006",
    entityName: "Yash Poojary",
    surface: "tiktok",
    label: "Tiktok",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_068",
    entityType: "employee",
    entityId: "emp_006",
    entityName: "Yash Poojary",
    surface: "product_hunt",
    label: "Product Hunt",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_069",
    entityType: "employee",
    entityId: "emp_006",
    entityName: "Yash Poojary",
    surface: "personal_site",
    label: "Personal Site",
    handle: null,
    url: null,
    status: "absent",
    notes: "No dedicated site.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_070",
    entityType: "employee",
    entityId: "emp_007",
    entityName: "Naveen Naidu",
    surface: "x",
    label: "X",
    handle: "@naveennaidu",
    url: "https://x.com/naveennaidu",
    status: "verified",
    notes: "Cultural tweets. 'Dia and Granola' style content.",
    confidenceScore: 0.85,
  },
  {
    id: "surf_071",
    entityType: "employee",
    entityId: "emp_007",
    entityName: "Naveen Naidu",
    surface: "linkedin",
    label: "Linkedin",
    handle: "naveen-naidu",
    url: "https://linkedin.com/in/naveen-naidu",
    status: "verified",
    notes: "Professional presence.",
    confidenceScore: 0.75,
  },
  {
    id: "surf_072",
    entityType: "employee",
    entityId: "emp_007",
    entityName: "Naveen Naidu",
    surface: "github",
    label: "Github",
    handle: null,
    url: null,
    status: "absent",
    notes: "No visible presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_073",
    entityType: "employee",
    entityId: "emp_007",
    entityName: "Naveen Naidu",
    surface: "substack",
    label: "Substack",
    handle: null,
    url: null,
    status: "absent",
    notes: "No dedicated newsletter.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_074",
    entityType: "employee",
    entityId: "emp_007",
    entityName: "Naveen Naidu",
    surface: "youtube",
    label: "Youtube",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_075",
    entityType: "employee",
    entityId: "emp_007",
    entityName: "Naveen Naidu",
    surface: "instagram",
    label: "Instagram",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_076",
    entityType: "employee",
    entityId: "emp_007",
    entityName: "Naveen Naidu",
    surface: "tiktok",
    label: "Tiktok",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_077",
    entityType: "employee",
    entityId: "emp_007",
    entityName: "Naveen Naidu",
    surface: "product_hunt",
    label: "Product Hunt",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_078",
    entityType: "employee",
    entityId: "emp_007",
    entityName: "Naveen Naidu",
    surface: "personal_site",
    label: "Personal Site",
    handle: null,
    url: null,
    status: "absent",
    notes: "No dedicated site.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_079",
    entityType: "employee",
    entityId: "emp_008",
    entityName: "Natalia Quintero",
    surface: "x",
    label: "X",
    handle: "@nataliaquintero",
    url: "https://x.com/nataliaquintero",
    status: "verified",
    notes: "Enterprise insights. Lower volume than LinkedIn.",
    confidenceScore: 0.78,
  },
  {
    id: "surf_080",
    entityType: "employee",
    entityId: "emp_008",
    entityName: "Natalia Quintero",
    surface: "linkedin",
    label: "Linkedin",
    handle: "natalia-quintero",
    url: "https://linkedin.com/in/natalia-quintero",
    status: "verified",
    notes: "Primary surface. Enterprise consulting content. Already generating leads in comments.",
    confidenceScore: 0.95,
  },
  {
    id: "surf_081",
    entityType: "employee",
    entityId: "emp_008",
    entityName: "Natalia Quintero",
    surface: "github",
    label: "Github",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_082",
    entityType: "employee",
    entityId: "emp_008",
    entityName: "Natalia Quintero",
    surface: "substack",
    label: "Substack",
    handle: null,
    url: null,
    status: "absent",
    notes: "No dedicated newsletter.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_083",
    entityType: "employee",
    entityId: "emp_008",
    entityName: "Natalia Quintero",
    surface: "youtube",
    label: "Youtube",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_084",
    entityType: "employee",
    entityId: "emp_008",
    entityName: "Natalia Quintero",
    surface: "instagram",
    label: "Instagram",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_085",
    entityType: "employee",
    entityId: "emp_008",
    entityName: "Natalia Quintero",
    surface: "tiktok",
    label: "Tiktok",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_086",
    entityType: "employee",
    entityId: "emp_008",
    entityName: "Natalia Quintero",
    surface: "product_hunt",
    label: "Product Hunt",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_087",
    entityType: "employee",
    entityId: "emp_008",
    entityName: "Natalia Quintero",
    surface: "personal_site",
    label: "Personal Site",
    handle: null,
    url: null,
    status: "absent",
    notes: "No dedicated site.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_088",
    entityType: "employee",
    entityId: "emp_009",
    entityName: "Katie Parrott",
    surface: "x",
    label: "X",
    handle: "@katieparrott",
    url: "https://x.com/katieparrott",
    status: "verified",
    notes: "Editorial threads. Complex topics made simple.",
    confidenceScore: 0.85,
  },
  {
    id: "surf_089",
    entityType: "employee",
    entityId: "emp_009",
    entityName: "Katie Parrott",
    surface: "linkedin",
    label: "Linkedin",
    handle: "katie-parrott",
    url: "https://linkedin.com/in/katie-parrott",
    status: "verified",
    notes: "Professional editorial presence.",
    confidenceScore: 0.78,
  },
  {
    id: "surf_090",
    entityType: "employee",
    entityId: "emp_009",
    entityName: "Katie Parrott",
    surface: "substack",
    label: "Substack",
    handle: "katieparrott",
    url: "https://katieparrott.substack.com",
    status: "verified",
    notes: "Personal newsletter. Editorial deep dives.",
    confidenceScore: 0.8,
  },
  {
    id: "surf_091",
    entityType: "employee",
    entityId: "emp_009",
    entityName: "Katie Parrott",
    surface: "github",
    label: "Github",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_092",
    entityType: "employee",
    entityId: "emp_009",
    entityName: "Katie Parrott",
    surface: "youtube",
    label: "Youtube",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_093",
    entityType: "employee",
    entityId: "emp_009",
    entityName: "Katie Parrott",
    surface: "instagram",
    label: "Instagram",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_094",
    entityType: "employee",
    entityId: "emp_009",
    entityName: "Katie Parrott",
    surface: "tiktok",
    label: "Tiktok",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_095",
    entityType: "employee",
    entityId: "emp_009",
    entityName: "Katie Parrott",
    surface: "product_hunt",
    label: "Product Hunt",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_096",
    entityType: "employee",
    entityId: "emp_009",
    entityName: "Katie Parrott",
    surface: "personal_site",
    label: "Personal Site",
    handle: null,
    url: null,
    status: "absent",
    notes: "No dedicated site.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_097",
    entityType: "employee",
    entityId: "emp_010",
    entityName: "Laura Entis",
    surface: "x",
    label: "X",
    handle: null,
    url: null,
    status: "absent",
    notes: "No Twitter presence. Major gap for a writer.",
    confidenceScore: 0.08,
  },
  {
    id: "surf_098",
    entityType: "employee",
    entityId: "emp_010",
    entityName: "Laura Entis",
    surface: "linkedin",
    label: "Linkedin",
    handle: "laura-entis",
    url: "https://linkedin.com/in/laura-entis",
    status: "verified",
    notes: "Professional presence. Article promotion.",
    confidenceScore: 0.82,
  },
  {
    id: "surf_099",
    entityType: "employee",
    entityId: "emp_010",
    entityName: "Laura Entis",
    surface: "substack",
    label: "Substack",
    handle: null,
    url: null,
    status: "absent",
    notes: "No dedicated newsletter.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_100",
    entityType: "employee",
    entityId: "emp_010",
    entityName: "Laura Entis",
    surface: "github",
    label: "Github",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_101",
    entityType: "employee",
    entityId: "emp_010",
    entityName: "Laura Entis",
    surface: "youtube",
    label: "Youtube",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_102",
    entityType: "employee",
    entityId: "emp_010",
    entityName: "Laura Entis",
    surface: "instagram",
    label: "Instagram",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_103",
    entityType: "employee",
    entityId: "emp_010",
    entityName: "Laura Entis",
    surface: "tiktok",
    label: "Tiktok",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_104",
    entityType: "employee",
    entityId: "emp_010",
    entityName: "Laura Entis",
    surface: "product_hunt",
    label: "Product Hunt",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_105",
    entityType: "employee",
    entityId: "emp_010",
    entityName: "Laura Entis",
    surface: "personal_site",
    label: "Personal Site",
    handle: null,
    url: null,
    status: "absent",
    notes: "No dedicated site.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_106",
    entityType: "employee",
    entityId: "emp_011",
    entityName: "Willie Williams",
    surface: "x",
    label: "X",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_107",
    entityType: "employee",
    entityId: "emp_011",
    entityName: "Willie Williams",
    surface: "linkedin",
    label: "Linkedin",
    handle: "willie-williams",
    url: "https://linkedin.com/in/willie-williams",
    status: "verified",
    notes: "Professional presence. Limited activity.",
    confidenceScore: 0.72,
  },
  {
    id: "surf_108",
    entityType: "employee",
    entityId: "emp_011",
    entityName: "Willie Williams",
    surface: "github",
    label: "Github",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_109",
    entityType: "employee",
    entityId: "emp_011",
    entityName: "Willie Williams",
    surface: "substack",
    label: "Substack",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_110",
    entityType: "employee",
    entityId: "emp_011",
    entityName: "Willie Williams",
    surface: "youtube",
    label: "Youtube",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_111",
    entityType: "employee",
    entityId: "emp_011",
    entityName: "Willie Williams",
    surface: "instagram",
    label: "Instagram",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_112",
    entityType: "employee",
    entityId: "emp_011",
    entityName: "Willie Williams",
    surface: "tiktok",
    label: "Tiktok",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_113",
    entityType: "employee",
    entityId: "emp_011",
    entityName: "Willie Williams",
    surface: "product_hunt",
    label: "Product Hunt",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_114",
    entityType: "employee",
    entityId: "emp_011",
    entityName: "Willie Williams",
    surface: "personal_site",
    label: "Personal Site",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_115",
    entityType: "employee",
    entityId: "emp_012",
    entityName: "Lucas Crespo",
    surface: "x",
    label: "X",
    handle: "@lucascrespo",
    url: "https://x.com/lucascrespo",
    status: "verified",
    notes: "Design content. Lower volume.",
    confidenceScore: 0.72,
  },
  {
    id: "surf_116",
    entityType: "employee",
    entityId: "emp_012",
    entityName: "Lucas Crespo",
    surface: "linkedin",
    label: "Linkedin",
    handle: "lucas-crespo",
    url: "https://linkedin.com/in/lucas-crespo",
    status: "verified",
    notes: "Professional design presence.",
    confidenceScore: 0.78,
  },
  {
    id: "surf_117",
    entityType: "employee",
    entityId: "emp_012",
    entityName: "Lucas Crespo",
    surface: "github",
    label: "Github",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_118",
    entityType: "employee",
    entityId: "emp_012",
    entityName: "Lucas Crespo",
    surface: "substack",
    label: "Substack",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_119",
    entityType: "employee",
    entityId: "emp_012",
    entityName: "Lucas Crespo",
    surface: "youtube",
    label: "Youtube",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_120",
    entityType: "employee",
    entityId: "emp_012",
    entityName: "Lucas Crespo",
    surface: "instagram",
    label: "Instagram",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_121",
    entityType: "employee",
    entityId: "emp_012",
    entityName: "Lucas Crespo",
    surface: "tiktok",
    label: "Tiktok",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_122",
    entityType: "employee",
    entityId: "emp_012",
    entityName: "Lucas Crespo",
    surface: "product_hunt",
    label: "Product Hunt",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_123",
    entityType: "employee",
    entityId: "emp_012",
    entityName: "Lucas Crespo",
    surface: "personal_site",
    label: "Personal Site",
    handle: null,
    url: null,
    status: "absent",
    notes: "No dedicated site.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_124",
    entityType: "employee",
    entityId: "emp_012",
    entityName: "Lucas Crespo",
    surface: "external_interview",
    label: "External Interview",
    handle: null,
    url: "https://design.blog/interview-lucas-crespo",
    status: "verified",
    notes: "External authority surface. Design interview.",
    confidenceScore: 0.85,
  },
  {
    id: "surf_125",
    entityType: "employee",
    entityId: "emp_013",
    entityName: "Mike Taylor",
    surface: "x",
    label: "X",
    handle: "@miketaylor",
    url: "https://x.com/miketaylor",
    status: "verified",
    notes: "Technical content. Lower volume than authority surfaces.",
    confidenceScore: 0.78,
  },
  {
    id: "surf_126",
    entityType: "employee",
    entityId: "emp_013",
    entityName: "Mike Taylor",
    surface: "linkedin",
    label: "Linkedin",
    handle: "mike-taylor",
    url: "https://linkedin.com/in/mike-taylor",
    status: "verified",
    notes: "Enterprise technical presence.",
    confidenceScore: 0.88,
  },
  {
    id: "surf_127",
    entityType: "employee",
    entityId: "emp_013",
    entityName: "Mike Taylor",
    surface: "github",
    label: "Github",
    handle: "miketaylor",
    url: "https://github.com/miketaylor",
    status: "verified",
    notes: "Technical repos. Moderate activity.",
    confidenceScore: 0.75,
  },
  {
    id: "surf_128",
    entityType: "employee",
    entityId: "emp_013",
    entityName: "Mike Taylor",
    surface: "substack",
    label: "Substack",
    handle: null,
    url: null,
    status: "absent",
    notes: "No dedicated newsletter.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_129",
    entityType: "employee",
    entityId: "emp_013",
    entityName: "Mike Taylor",
    surface: "youtube",
    label: "Youtube",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_130",
    entityType: "employee",
    entityId: "emp_013",
    entityName: "Mike Taylor",
    surface: "instagram",
    label: "Instagram",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_131",
    entityType: "employee",
    entityId: "emp_013",
    entityName: "Mike Taylor",
    surface: "tiktok",
    label: "Tiktok",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_132",
    entityType: "employee",
    entityId: "emp_013",
    entityName: "Mike Taylor",
    surface: "product_hunt",
    label: "Product Hunt",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_133",
    entityType: "employee",
    entityId: "emp_013",
    entityName: "Mike Taylor",
    surface: "personal_site",
    label: "Personal Site",
    handle: null,
    url: null,
    status: "absent",
    notes: "No dedicated site.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_134",
    entityType: "employee",
    entityId: "emp_013",
    entityName: "Mike Taylor",
    surface: "book",
    label: "Book",
    handle: null,
    url: "https://oreilly.com/library/view/mike-taylor",
    status: "verified",
    notes: "O'Reilly book. Major authority surface.",
    confidenceScore: 0.98,
  },
  {
    id: "surf_135",
    entityType: "employee",
    entityId: "emp_014",
    entityName: "Alex Duffy",
    surface: "x",
    label: "X",
    handle: "@alexduffy",
    url: "https://x.com/alexduffy",
    status: "verified",
    notes: "Technical content. Lower volume.",
    confidenceScore: 0.72,
  },
  {
    id: "surf_136",
    entityType: "employee",
    entityId: "emp_014",
    entityName: "Alex Duffy",
    surface: "linkedin",
    label: "Linkedin",
    handle: "alex-duffy",
    url: "https://linkedin.com/in/alex-duffy",
    status: "verified",
    notes: "Professional presence.",
    confidenceScore: 0.7,
  },
  {
    id: "surf_137",
    entityType: "employee",
    entityId: "emp_014",
    entityName: "Alex Duffy",
    surface: "github",
    label: "Github",
    handle: "alexduffy",
    url: "https://github.com/alexduffy",
    status: "verified",
    notes: "Technical repos.",
    confidenceScore: 0.78,
  },
  {
    id: "surf_138",
    entityType: "employee",
    entityId: "emp_014",
    entityName: "Alex Duffy",
    surface: "substack",
    label: "Substack",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_139",
    entityType: "employee",
    entityId: "emp_014",
    entityName: "Alex Duffy",
    surface: "youtube",
    label: "Youtube",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_140",
    entityType: "employee",
    entityId: "emp_014",
    entityName: "Alex Duffy",
    surface: "instagram",
    label: "Instagram",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_141",
    entityType: "employee",
    entityId: "emp_014",
    entityName: "Alex Duffy",
    surface: "tiktok",
    label: "Tiktok",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_142",
    entityType: "employee",
    entityId: "emp_014",
    entityName: "Alex Duffy",
    surface: "product_hunt",
    label: "Product Hunt",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_143",
    entityType: "employee",
    entityId: "emp_014",
    entityName: "Alex Duffy",
    surface: "personal_site",
    label: "Personal Site",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_144",
    entityType: "employee",
    entityId: "emp_015",
    entityName: "Rhea Purohit",
    surface: "x",
    label: "X",
    handle: "@rheapurohit",
    url: "https://x.com/rheapurohit",
    status: "verified",
    notes: "Growth content. Campaign updates.",
    confidenceScore: 0.78,
  },
  {
    id: "surf_145",
    entityType: "employee",
    entityId: "emp_015",
    entityName: "Rhea Purohit",
    surface: "linkedin",
    label: "Linkedin",
    handle: "rhea-purohit",
    url: "https://linkedin.com/in/rhea-purohit",
    status: "verified",
    notes: "Professional growth presence.",
    confidenceScore: 0.75,
  },
  {
    id: "surf_146",
    entityType: "employee",
    entityId: "emp_015",
    entityName: "Rhea Purohit",
    surface: "github",
    label: "Github",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_147",
    entityType: "employee",
    entityId: "emp_015",
    entityName: "Rhea Purohit",
    surface: "substack",
    label: "Substack",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_148",
    entityType: "employee",
    entityId: "emp_015",
    entityName: "Rhea Purohit",
    surface: "youtube",
    label: "Youtube",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_149",
    entityType: "employee",
    entityId: "emp_015",
    entityName: "Rhea Purohit",
    surface: "instagram",
    label: "Instagram",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_150",
    entityType: "employee",
    entityId: "emp_015",
    entityName: "Rhea Purohit",
    surface: "tiktok",
    label: "Tiktok",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_151",
    entityType: "employee",
    entityId: "emp_015",
    entityName: "Rhea Purohit",
    surface: "product_hunt",
    label: "Product Hunt",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_152",
    entityType: "employee",
    entityId: "emp_015",
    entityName: "Rhea Purohit",
    surface: "personal_site",
    label: "Personal Site",
    handle: "rheapurohit.com",
    url: "https://rheapurohit.com",
    status: "verified",
    notes: "Personal site. Growth portfolio + case studies.",
    confidenceScore: 0.82,
  },
  {
    id: "surf_153",
    entityType: "employee",
    entityId: "emp_016",
    entityName: "Anthony Scarpulla",
    surface: "x",
    label: "X",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_154",
    entityType: "employee",
    entityId: "emp_016",
    entityName: "Anthony Scarpulla",
    surface: "linkedin",
    label: "Linkedin",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.08,
  },
  {
    id: "surf_155",
    entityType: "employee",
    entityId: "emp_016",
    entityName: "Anthony Scarpulla",
    surface: "github",
    label: "Github",
    handle: null,
    url: null,
    status: "absent",
    notes: "No visible presence.",
    confidenceScore: 0.1,
  },
  {
    id: "surf_156",
    entityType: "employee",
    entityId: "emp_016",
    entityName: "Anthony Scarpulla",
    surface: "substack",
    label: "Substack",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_157",
    entityType: "employee",
    entityId: "emp_016",
    entityName: "Anthony Scarpulla",
    surface: "youtube",
    label: "Youtube",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_158",
    entityType: "employee",
    entityId: "emp_016",
    entityName: "Anthony Scarpulla",
    surface: "instagram",
    label: "Instagram",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_159",
    entityType: "employee",
    entityId: "emp_016",
    entityName: "Anthony Scarpulla",
    surface: "tiktok",
    label: "Tiktok",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_160",
    entityType: "employee",
    entityId: "emp_016",
    entityName: "Anthony Scarpulla",
    surface: "product_hunt",
    label: "Product Hunt",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
  {
    id: "surf_161",
    entityType: "employee",
    entityId: "emp_016",
    entityName: "Anthony Scarpulla",
    surface: "personal_site",
    label: "Personal Site",
    handle: null,
    url: null,
    status: "absent",
    notes: "No presence.",
    confidenceScore: 0.05,
  },
];
