export const THREE_POINT_SIGNALS = [
  "book a demo",
  "book demo",
  "schedule a demo",
  "buy now",
  "purchase",
  "subscribe",
  "join waitlist",
  "get early access",
  "request access",
  "enterprise",
  "consulting inquiry",
  "talk to sales",
  "contact sales",
  "every.to/consulting",
  "/checkout",
  "/pricing",
  "try sparkle",
];

export const MID_RANGE_SIGNALS = [
  "sign up",
  "signup",
  "join the newsletter",
  "free trial",
  "try free",
  "free for",
  "join the waitlist",
  "early access",
  "subscribe to",
  "newsletter",
  "every.to/",
  "subscribe at",
  "join us at",
];

export const PAINT_SIGNALS = [
  "follow @",
  "follow me",
  "like this if",
  "rt if",
  "retweet if",
  "comment below",
  "what do you think",
  "thoughts?",
  "agree?",
  "let me know",
  "drop a",
  "share if",
  "share this",
];

export const FREE_THROW_SIGNALS = [
  "weekend",
  "morning",
  "reading",
  "cooking",
  "running",
  "kids",
  "family",
  "vacation",
  "birthday",
  "happy birthday",
  "nba",
  "nfl",
  "espn",
  "playoffs",
  "world cup",
  "street food",
  "sourdough",
];

export const PASS_SIGNALS = [
  "thread",
  "1/",
  "let me explain",
  "here's why",
  "in my opinion",
  "the way i think about",
  "framework for",
  "my mental model",
  "the future of",
  "i believe",
  "thesis",
  "hypothesis",
  "underrated for creative work",
];

export const ASSIST_SIGNALS = [
  "@every",
  "@danshipper",
  "@tedescau",
  "@kieranklaassen",
  "@kate_1767",
  "@katelaurielee",
  "@poojary_yash",
  "@naveennaidu_m",
  "@kplikethebird",
  "@lauraentis",
  "@bran_don_gell",
  "@NataliaZarina",
  "@bigwilliestyle",
  "@lucas__crespo",
  "@hammer_mt",
  "@alxai_",
  "@RheaPurohit1",
  "great piece by",
  "great piece on",
  "must read from",
  "shoutout to",
  "via @",
];

export const TURNOVER_SIGNALS = ["broken link", "404", "doesn't work", "scam", "spam", "unfollow", "muted", "blocked"];

export const WORK_SIGNALS = [
  "ai",
  "product",
  "building",
  "startup",
  "code",
  "engineering",
  "design",
  "growth",
  "marketing",
  "founder",
  "ceo",
  "software",
  "agent",
  "work",
];
